# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/Sensor Monitor Board/Software/RaspberryPi/ICS_SMB/SmbMainGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(974, 686)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setGeometry(QtCore.QRect(50, 20, 581, 611))
        self.tabMain.setBaseSize(QtCore.QSize(0, 0))
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabReadings = QtGui.QWidget()
        self.tabReadings.setObjectName(_fromUtf8("tabReadings"))
        self.btnReadAdcCounts = QtGui.QPushButton(self.tabReadings)
        self.btnReadAdcCounts.setGeometry(QtCore.QRect(40, 60, 131, 31))
        self.btnReadAdcCounts.setObjectName(_fromUtf8("btnReadAdcCounts"))
        self.btnReadSensorResistances = QtGui.QPushButton(self.tabReadings)
        self.btnReadSensorResistances.setGeometry(QtCore.QRect(40, 150, 131, 41))
        self.btnReadSensorResistances.setObjectName(_fromUtf8("btnReadSensorResistances"))
        self.btnReadSenorVolts = QtGui.QPushButton(self.tabReadings)
        self.btnReadSenorVolts.setGeometry(QtCore.QRect(40, 100, 131, 41))
        self.btnReadSenorVolts.setObjectName(_fromUtf8("btnReadSenorVolts"))
        self.btnReadAllTemps = QtGui.QPushButton(self.tabReadings)
        self.btnReadAllTemps.setGeometry(QtCore.QRect(40, 10, 131, 41))
        self.btnReadAllTemps.setObjectName(_fromUtf8("btnReadAllTemps"))
        self.btnReadHumidity = QtGui.QPushButton(self.tabReadings)
        self.btnReadHumidity.setGeometry(QtCore.QRect(40, 300, 131, 31))
        self.btnReadHumidity.setObjectName(_fromUtf8("btnReadHumidity"))
        self.btnRadRefVolts = QtGui.QPushButton(self.tabReadings)
        self.btnRadRefVolts.setGeometry(QtCore.QRect(40, 200, 131, 41))
        self.btnRadRefVolts.setObjectName(_fromUtf8("btnRadRefVolts"))
        self.btnReadAdcChipTemps = QtGui.QPushButton(self.tabReadings)
        self.btnReadAdcChipTemps.setGeometry(QtCore.QRect(40, 250, 131, 41))
        self.btnReadAdcChipTemps.setObjectName(_fromUtf8("btnReadAdcChipTemps"))
        self.tabMain.addTab(self.tabReadings, _fromUtf8(""))
        self.tabAdcConfig = QtGui.QWidget()
        self.tabAdcConfig.setObjectName(_fromUtf8("tabAdcConfig"))
        self.grpAdcs = QtGui.QGroupBox(self.tabAdcConfig)
        self.grpAdcs.setGeometry(QtCore.QRect(20, 20, 91, 261))
        self.grpAdcs.setCheckable(False)
        self.grpAdcs.setObjectName(_fromUtf8("grpAdcs"))
        self.chkAdc1 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.chkAdc1.setObjectName(_fromUtf8("chkAdc1"))
        self.chkAdc2 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.chkAdc2.setObjectName(_fromUtf8("chkAdc2"))
        self.chkAdc3 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.chkAdc3.setObjectName(_fromUtf8("chkAdc3"))
        self.chkAdc4 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc4.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.chkAdc4.setObjectName(_fromUtf8("chkAdc4"))
        self.chkAdc8 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc8.setGeometry(QtCore.QRect(20, 160, 71, 20))
        self.chkAdc8.setObjectName(_fromUtf8("chkAdc8"))
        self.chkAdc5 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc5.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.chkAdc5.setObjectName(_fromUtf8("chkAdc5"))
        self.chkAdc7 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc7.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.chkAdc7.setObjectName(_fromUtf8("chkAdc7"))
        self.chkAdc6 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc6.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.chkAdc6.setObjectName(_fromUtf8("chkAdc6"))
        self.chkAdc12 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc12.setGeometry(QtCore.QRect(20, 240, 71, 20))
        self.chkAdc12.setObjectName(_fromUtf8("chkAdc12"))
        self.chkAdc9 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc9.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.chkAdc9.setObjectName(_fromUtf8("chkAdc9"))
        self.chkAdc11 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc11.setGeometry(QtCore.QRect(20, 220, 70, 17))
        self.chkAdc11.setObjectName(_fromUtf8("chkAdc11"))
        self.chkAdc10 = QtGui.QCheckBox(self.grpAdcs)
        self.chkAdc10.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chkAdc10.setObjectName(_fromUtf8("chkAdc10"))
        self.cboExciationCurrent = QtGui.QComboBox(self.tabAdcConfig)
        self.cboExciationCurrent.setGeometry(QtCore.QRect(120, 50, 121, 22))
        self.cboExciationCurrent.setObjectName(_fromUtf8("cboExciationCurrent"))
        self.cboExciationCurrent.addItem(_fromUtf8(""))
        self.cboExciationCurrent.addItem(_fromUtf8(""))
        self.cboExciationCurrent.addItem(_fromUtf8(""))
        self.cboExciationCurrent.addItem(_fromUtf8(""))
        self.cboExciationCurrent.addItem(_fromUtf8(""))
        self.cboExciationCurrent.addItem(_fromUtf8(""))
        self.lblCboExcitationCurent = QtGui.QLabel(self.tabAdcConfig)
        self.lblCboExcitationCurent.setGeometry(QtCore.QRect(120, 30, 121, 16))
        self.lblCboExcitationCurent.setObjectName(_fromUtf8("lblCboExcitationCurent"))
        self.lblCboAdcPostFilter = QtGui.QLabel(self.tabAdcConfig)
        self.lblCboAdcPostFilter.setGeometry(QtCore.QRect(120, 140, 121, 16))
        self.lblCboAdcPostFilter.setObjectName(_fromUtf8("lblCboAdcPostFilter"))
        self.cboSelectAdcPostFilter = QtGui.QComboBox(self.tabAdcConfig)
        self.cboSelectAdcPostFilter.setGeometry(QtCore.QRect(120, 160, 121, 22))
        self.cboSelectAdcPostFilter.setObjectName(_fromUtf8("cboSelectAdcPostFilter"))
        self.cboSelectAdcPostFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcPostFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcPostFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcPostFilter.addItem(_fromUtf8(""))
        self.lblCboAdcSincFilter = QtGui.QLabel(self.tabAdcConfig)
        self.lblCboAdcSincFilter.setGeometry(QtCore.QRect(120, 90, 121, 16))
        self.lblCboAdcSincFilter.setObjectName(_fromUtf8("lblCboAdcSincFilter"))
        self.cboSelectAdcSincFilter = QtGui.QComboBox(self.tabAdcConfig)
        self.cboSelectAdcSincFilter.setGeometry(QtCore.QRect(120, 110, 121, 22))
        self.cboSelectAdcSincFilter.setObjectName(_fromUtf8("cboSelectAdcSincFilter"))
        self.cboSelectAdcSincFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcSincFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcSincFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcSincFilter.addItem(_fromUtf8(""))
        self.cboSelectAdcSincFilter.addItem(_fromUtf8(""))
        self.chkRej60 = QtGui.QCheckBox(self.tabAdcConfig)
        self.chkRej60.setGeometry(QtCore.QRect(120, 200, 111, 17))
        self.chkRej60.setObjectName(_fromUtf8("chkRej60"))
        self.lblCboAdcFilterDataRate = QtGui.QLabel(self.tabAdcConfig)
        self.lblCboAdcFilterDataRate.setGeometry(QtCore.QRect(120, 230, 191, 16))
        self.lblCboAdcFilterDataRate.setObjectName(_fromUtf8("lblCboAdcFilterDataRate"))
        self.spinAdcFilterDataRate = QtGui.QSpinBox(self.tabAdcConfig)
        self.spinAdcFilterDataRate.setGeometry(QtCore.QRect(120, 250, 121, 22))
        self.spinAdcFilterDataRate.setMinimum(1)
        self.spinAdcFilterDataRate.setMaximum(2047)
        self.spinAdcFilterDataRate.setObjectName(_fromUtf8("spinAdcFilterDataRate"))
        self.btnSetFilterDataRate = QtGui.QPushButton(self.tabAdcConfig)
        self.btnSetFilterDataRate.setGeometry(QtCore.QRect(250, 250, 61, 23))
        self.btnSetFilterDataRate.setObjectName(_fromUtf8("btnSetFilterDataRate"))
        self.tabMain.addTab(self.tabAdcConfig, _fromUtf8(""))
        self.tabHeaterLoops = QtGui.QWidget()
        self.tabHeaterLoops.setObjectName(_fromUtf8("tabHeaterLoops"))
        self.btnReadLoop1Settings = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnReadLoop1Settings.setGeometry(QtCore.QRect(30, 20, 151, 31))
        self.btnReadLoop1Settings.setObjectName(_fromUtf8("btnReadLoop1Settings"))
        self.btnReadLoop2Settings = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnReadLoop2Settings.setGeometry(QtCore.QRect(390, 20, 151, 31))
        self.btnReadLoop2Settings.setObjectName(_fromUtf8("btnReadLoop2Settings"))
        self.SpinDblPterm1 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblPterm1.setGeometry(QtCore.QRect(130, 80, 101, 22))
        self.SpinDblPterm1.setMaximum(100.0)
        self.SpinDblPterm1.setObjectName(_fromUtf8("SpinDblPterm1"))
        self.lblProportional1 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblProportional1.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.lblProportional1.setObjectName(_fromUtf8("lblProportional1"))
        self.btnSetPterm1 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetPterm1.setGeometry(QtCore.QRect(240, 80, 41, 21))
        self.btnSetPterm1.setObjectName(_fromUtf8("btnSetPterm1"))
        self.lblIntegral1 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblIntegral1.setGeometry(QtCore.QRect(30, 110, 91, 16))
        self.lblIntegral1.setObjectName(_fromUtf8("lblIntegral1"))
        self.btnSetIterm1 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetIterm1.setGeometry(QtCore.QRect(240, 110, 41, 21))
        self.btnSetIterm1.setObjectName(_fromUtf8("btnSetIterm1"))
        self.SpinDblIterm1 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblIterm1.setGeometry(QtCore.QRect(130, 110, 101, 22))
        self.SpinDblIterm1.setMaximum(100.0)
        self.SpinDblIterm1.setObjectName(_fromUtf8("SpinDblIterm1"))
        self.btnSetDterm1 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetDterm1.setGeometry(QtCore.QRect(240, 140, 41, 21))
        self.btnSetDterm1.setObjectName(_fromUtf8("btnSetDterm1"))
        self.lblDerivative1 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblDerivative1.setGeometry(QtCore.QRect(20, 140, 101, 20))
        self.lblDerivative1.setObjectName(_fromUtf8("lblDerivative1"))
        self.SpinDblDterm1 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblDterm1.setGeometry(QtCore.QRect(130, 140, 101, 22))
        self.SpinDblDterm1.setMaximum(100.0)
        self.SpinDblDterm1.setObjectName(_fromUtf8("SpinDblDterm1"))
        self.lblSelLoopSns1 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblSelLoopSns1.setGeometry(QtCore.QRect(20, 180, 101, 20))
        self.lblSelLoopSns1.setObjectName(_fromUtf8("lblSelLoopSns1"))
        self.cboSelLoopSns1 = QtGui.QComboBox(self.tabHeaterLoops)
        self.cboSelLoopSns1.setGeometry(QtCore.QRect(130, 180, 91, 22))
        self.cboSelLoopSns1.setObjectName(_fromUtf8("cboSelLoopSns1"))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.cboSelLoopSns1.addItem(_fromUtf8(""))
        self.SpinDblSetPoint1 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblSetPoint1.setGeometry(QtCore.QRect(130, 220, 101, 22))
        self.SpinDblSetPoint1.setMinimum(-273.0)
        self.SpinDblSetPoint1.setMaximum(500.0)
        self.SpinDblSetPoint1.setObjectName(_fromUtf8("SpinDblSetPoint1"))
        self.lblSetPoint1 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblSetPoint1.setGeometry(QtCore.QRect(60, 220, 61, 20))
        self.lblSetPoint1.setObjectName(_fromUtf8("lblSetPoint1"))
        self.btnSetSp1 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetSp1.setGeometry(QtCore.QRect(240, 220, 41, 21))
        self.btnSetSp1.setObjectName(_fromUtf8("btnSetSp1"))
        self.lblHtrCruuent1 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblHtrCruuent1.setGeometry(QtCore.QRect(30, 250, 91, 20))
        self.lblHtrCruuent1.setObjectName(_fromUtf8("lblHtrCruuent1"))
        self.btnSetHtrCurrent1 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetHtrCurrent1.setGeometry(QtCore.QRect(240, 250, 41, 21))
        self.btnSetHtrCurrent1.setObjectName(_fromUtf8("btnSetHtrCurrent1"))
        self.SpinHtrCurrent1 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinHtrCurrent1.setGeometry(QtCore.QRect(130, 250, 101, 22))
        self.SpinHtrCurrent1.setDecimals(3)
        self.SpinHtrCurrent1.setMaximum(0.1)
        self.SpinHtrCurrent1.setSingleStep(0.001)
        self.SpinHtrCurrent1.setObjectName(_fromUtf8("SpinHtrCurrent1"))
        self.radDisabled1 = QtGui.QRadioButton(self.tabHeaterLoops)
        self.radDisabled1.setGeometry(QtCore.QRect(130, 300, 82, 17))
        self.radDisabled1.setChecked(True)
        self.radDisabled1.setObjectName(_fromUtf8("radDisabled1"))
        self.groupHtrCtl = QtGui.QButtonGroup(MainWindow)
        self.groupHtrCtl.setObjectName(_fromUtf8("groupHtrCtl"))
        self.groupHtrCtl.addButton(self.radDisabled1)
        self.radHtrCurrent1 = QtGui.QRadioButton(self.tabHeaterLoops)
        self.radHtrCurrent1.setGeometry(QtCore.QRect(130, 320, 82, 17))
        self.radHtrCurrent1.setObjectName(_fromUtf8("radHtrCurrent1"))
        self.groupHtrCtl.addButton(self.radHtrCurrent1)
        self.radPid1 = QtGui.QRadioButton(self.tabHeaterLoops)
        self.radPid1.setGeometry(QtCore.QRect(130, 340, 82, 17))
        self.radPid1.setObjectName(_fromUtf8("radPid1"))
        self.groupHtrCtl.addButton(self.radPid1)
        self.SpinDblDterm2 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblDterm2.setGeometry(QtCore.QRect(410, 140, 101, 22))
        self.SpinDblDterm2.setMaximum(100.0)
        self.SpinDblDterm2.setObjectName(_fromUtf8("SpinDblDterm2"))
        self.lblIntegral1_2 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblIntegral1_2.setGeometry(QtCore.QRect(310, 110, 91, 16))
        self.lblIntegral1_2.setObjectName(_fromUtf8("lblIntegral1_2"))
        self.lblProportional1_2 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblProportional1_2.setGeometry(QtCore.QRect(300, 80, 111, 16))
        self.lblProportional1_2.setObjectName(_fromUtf8("lblProportional1_2"))
        self.radPid2 = QtGui.QRadioButton(self.tabHeaterLoops)
        self.radPid2.setGeometry(QtCore.QRect(410, 340, 82, 17))
        self.radPid2.setObjectName(_fromUtf8("radPid2"))
        self.SpinDblSetPoint2 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblSetPoint2.setGeometry(QtCore.QRect(410, 220, 101, 22))
        self.SpinDblSetPoint2.setMinimum(-273.0)
        self.SpinDblSetPoint2.setMaximum(500.0)
        self.SpinDblSetPoint2.setObjectName(_fromUtf8("SpinDblSetPoint2"))
        self.SpinDblIterm2 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblIterm2.setGeometry(QtCore.QRect(410, 110, 101, 22))
        self.SpinDblIterm2.setMaximum(100.0)
        self.SpinDblIterm2.setObjectName(_fromUtf8("SpinDblIterm2"))
        self.lblSetPoint1_2 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblSetPoint1_2.setGeometry(QtCore.QRect(340, 220, 61, 20))
        self.lblSetPoint1_2.setObjectName(_fromUtf8("lblSetPoint1_2"))
        self.cboSelLoopSns2 = QtGui.QComboBox(self.tabHeaterLoops)
        self.cboSelLoopSns2.setGeometry(QtCore.QRect(410, 180, 91, 22))
        self.cboSelLoopSns2.setObjectName(_fromUtf8("cboSelLoopSns2"))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.cboSelLoopSns2.addItem(_fromUtf8(""))
        self.lblHtrCruuent1_2 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblHtrCruuent1_2.setGeometry(QtCore.QRect(310, 250, 91, 20))
        self.lblHtrCruuent1_2.setObjectName(_fromUtf8("lblHtrCruuent1_2"))
        self.btnSetHtrCurrent2 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetHtrCurrent2.setGeometry(QtCore.QRect(520, 250, 41, 21))
        self.btnSetHtrCurrent2.setObjectName(_fromUtf8("btnSetHtrCurrent2"))
        self.lblDerivative1_2 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblDerivative1_2.setGeometry(QtCore.QRect(300, 140, 101, 20))
        self.lblDerivative1_2.setObjectName(_fromUtf8("lblDerivative1_2"))
        self.SpinDblPterm2 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblPterm2.setGeometry(QtCore.QRect(410, 80, 101, 22))
        self.SpinDblPterm2.setMaximum(100.0)
        self.SpinDblPterm2.setObjectName(_fromUtf8("SpinDblPterm2"))
        self.radDisabled2 = QtGui.QRadioButton(self.tabHeaterLoops)
        self.radDisabled2.setGeometry(QtCore.QRect(410, 300, 82, 17))
        self.radDisabled2.setChecked(True)
        self.radDisabled2.setObjectName(_fromUtf8("radDisabled2"))
        self.SpinHtrCurrent2 = QtGui.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinHtrCurrent2.setGeometry(QtCore.QRect(410, 250, 101, 22))
        self.SpinHtrCurrent2.setDecimals(3)
        self.SpinHtrCurrent2.setMaximum(0.1)
        self.SpinHtrCurrent2.setSingleStep(0.001)
        self.SpinHtrCurrent2.setObjectName(_fromUtf8("SpinHtrCurrent2"))
        self.radHtrCurrent2 = QtGui.QRadioButton(self.tabHeaterLoops)
        self.radHtrCurrent2.setGeometry(QtCore.QRect(410, 320, 82, 17))
        self.radHtrCurrent2.setObjectName(_fromUtf8("radHtrCurrent2"))
        self.btnSetDterm2 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetDterm2.setGeometry(QtCore.QRect(520, 140, 41, 21))
        self.btnSetDterm2.setObjectName(_fromUtf8("btnSetDterm2"))
        self.btnSetPterm2 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetPterm2.setGeometry(QtCore.QRect(520, 80, 41, 21))
        self.btnSetPterm2.setObjectName(_fromUtf8("btnSetPterm2"))
        self.btnSetSp2 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetSp2.setGeometry(QtCore.QRect(520, 220, 41, 21))
        self.btnSetSp2.setObjectName(_fromUtf8("btnSetSp2"))
        self.lblSelLoopSns1_2 = QtGui.QLabel(self.tabHeaterLoops)
        self.lblSelLoopSns1_2.setGeometry(QtCore.QRect(300, 180, 101, 20))
        self.lblSelLoopSns1_2.setObjectName(_fromUtf8("lblSelLoopSns1_2"))
        self.btnSetIterm2 = QtGui.QPushButton(self.tabHeaterLoops)
        self.btnSetIterm2.setGeometry(QtCore.QRect(520, 110, 41, 21))
        self.btnSetIterm2.setObjectName(_fromUtf8("btnSetIterm2"))
        self.line = QtGui.QFrame(self.tabHeaterLoops)
        self.line.setGeometry(QtCore.QRect(280, 20, 20, 391))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.chkHighPowerOut1 = QtGui.QCheckBox(self.tabHeaterLoops)
        self.chkHighPowerOut1.setGeometry(QtCore.QRect(70, 460, 121, 17))
        self.chkHighPowerOut1.setObjectName(_fromUtf8("chkHighPowerOut1"))
        self.chkHighPowerOut2 = QtGui.QCheckBox(self.tabHeaterLoops)
        self.chkHighPowerOut2.setGeometry(QtCore.QRect(70, 480, 121, 17))
        self.chkHighPowerOut2.setObjectName(_fromUtf8("chkHighPowerOut2"))
        self.bthHighPowerOutStatus = QtGui.QPushButton(self.tabHeaterLoops)
        self.bthHighPowerOutStatus.setGeometry(QtCore.QRect(70, 510, 91, 23))
        self.bthHighPowerOutStatus.setObjectName(_fromUtf8("bthHighPowerOutStatus"))
        self.btnReadLoop1Settings.raise_()
        self.btnReadLoop2Settings.raise_()
        self.SpinDblPterm1.raise_()
        self.lblProportional1.raise_()
        self.btnSetPterm1.raise_()
        self.lblIntegral1.raise_()
        self.btnSetIterm1.raise_()
        self.SpinDblIterm1.raise_()
        self.btnSetDterm1.raise_()
        self.lblDerivative1.raise_()
        self.SpinDblDterm1.raise_()
        self.lblSelLoopSns1.raise_()
        self.cboSelLoopSns1.raise_()
        self.SpinDblSetPoint1.raise_()
        self.lblSetPoint1.raise_()
        self.btnSetSp1.raise_()
        self.lblHtrCruuent1.raise_()
        self.btnSetHtrCurrent1.raise_()
        self.SpinHtrCurrent1.raise_()
        self.radPid1.raise_()
        self.radHtrCurrent1.raise_()
        self.radDisabled1.raise_()
        self.SpinDblDterm2.raise_()
        self.lblIntegral1_2.raise_()
        self.lblProportional1_2.raise_()
        self.radPid2.raise_()
        self.SpinDblSetPoint2.raise_()
        self.SpinDblIterm2.raise_()
        self.lblSetPoint1_2.raise_()
        self.cboSelLoopSns2.raise_()
        self.lblHtrCruuent1_2.raise_()
        self.btnSetHtrCurrent2.raise_()
        self.lblDerivative1_2.raise_()
        self.SpinDblPterm2.raise_()
        self.radDisabled2.raise_()
        self.SpinHtrCurrent2.raise_()
        self.radHtrCurrent2.raise_()
        self.btnSetDterm2.raise_()
        self.btnSetPterm2.raise_()
        self.btnSetSp2.raise_()
        self.lblSelLoopSns1_2.raise_()
        self.btnSetIterm2.raise_()
        self.line.raise_()
        self.chkHighPowerOut1.raise_()
        self.chkHighPowerOut2.raise_()
        self.bthHighPowerOutStatus.raise_()
        self.tabMain.addTab(self.tabHeaterLoops, _fromUtf8(""))
        self.tabDatabase = QtGui.QWidget()
        self.tabDatabase.setObjectName(_fromUtf8("tabDatabase"))
        self.tableView = QtGui.QTableView(self.tabDatabase)
        self.tableView.setGeometry(QtCore.QRect(10, 50, 501, 521))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.cboDatabaseTableNames = QtGui.QComboBox(self.tabDatabase)
        self.cboDatabaseTableNames.setGeometry(QtCore.QRect(20, 10, 301, 22))
        self.cboDatabaseTableNames.setObjectName(_fromUtf8("cboDatabaseTableNames"))
        self.tabMain.addTab(self.tabDatabase, _fromUtf8(""))
        self.txtDisplay = QtGui.QTextBrowser(self.centralwidget)
        self.txtDisplay.setGeometry(QtCore.QRect(640, 40, 291, 591))
        self.txtDisplay.setObjectName(_fromUtf8("txtDisplay"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor Monitor Board", None))
        self.btnReadAdcCounts.setText(_translate("MainWindow", "Read A/D Counts", None))
        self.btnReadSensorResistances.setText(_translate("MainWindow", "Read RTD \n"
"Resistances", None))
        self.btnReadSenorVolts.setText(_translate("MainWindow", "Read RTD\n"
"Voltages", None))
        self.btnReadAllTemps.setText(_translate("MainWindow", "Read RTD\n"
"Temperatures", None))
        self.btnReadHumidity.setText(_translate("MainWindow", "Read Humidity", None))
        self.btnRadRefVolts.setText(_translate("MainWindow", "Read ADC \n"
" Ref Voltages", None))
        self.btnReadAdcChipTemps.setText(_translate("MainWindow", "Read ADC \n"
"Chip Temperatures", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabReadings), _translate("MainWindow", "Take Readings", None))
        self.grpAdcs.setTitle(_translate("MainWindow", "Select ADCs", None))
        self.chkAdc1.setText(_translate("MainWindow", "ADC 1", None))
        self.chkAdc2.setText(_translate("MainWindow", "ADC 2", None))
        self.chkAdc3.setText(_translate("MainWindow", "ADC 3", None))
        self.chkAdc4.setText(_translate("MainWindow", "ADC 4", None))
        self.chkAdc8.setText(_translate("MainWindow", "ADC 8", None))
        self.chkAdc5.setText(_translate("MainWindow", "ADC 5", None))
        self.chkAdc7.setText(_translate("MainWindow", "ADC 7", None))
        self.chkAdc6.setText(_translate("MainWindow", "ADC 6", None))
        self.chkAdc12.setText(_translate("MainWindow", "ADC 12", None))
        self.chkAdc9.setText(_translate("MainWindow", "ADC 9", None))
        self.chkAdc11.setText(_translate("MainWindow", "ADC 11", None))
        self.chkAdc10.setText(_translate("MainWindow", "ADC 10", None))
        self.cboExciationCurrent.setItemText(0, _translate("MainWindow", "NONE", None))
        self.cboExciationCurrent.setItemText(1, _translate("MainWindow", "50uA", None))
        self.cboExciationCurrent.setItemText(2, _translate("MainWindow", "100uA", None))
        self.cboExciationCurrent.setItemText(3, _translate("MainWindow", "250uA", None))
        self.cboExciationCurrent.setItemText(4, _translate("MainWindow", "500uA", None))
        self.cboExciationCurrent.setItemText(5, _translate("MainWindow", "1mA", None))
        self.lblCboExcitationCurent.setText(_translate("MainWindow", "Excitation Current", None))
        self.lblCboAdcPostFilter.setText(_translate("MainWindow", "Select ADC Post Filter", None))
        self.cboSelectAdcPostFilter.setItemText(0, _translate("MainWindow", "47dB", None))
        self.cboSelectAdcPostFilter.setItemText(1, _translate("MainWindow", "62dB", None))
        self.cboSelectAdcPostFilter.setItemText(2, _translate("MainWindow", "86dB", None))
        self.cboSelectAdcPostFilter.setItemText(3, _translate("MainWindow", "92dB", None))
        self.lblCboAdcSincFilter.setText(_translate("MainWindow", "Select ADC Sinc Filter", None))
        self.cboSelectAdcSincFilter.setItemText(0, _translate("MainWindow", "Sinc4", None))
        self.cboSelectAdcSincFilter.setItemText(1, _translate("MainWindow", "Sinc3", None))
        self.cboSelectAdcSincFilter.setItemText(2, _translate("MainWindow", "Sinc4 Fast", None))
        self.cboSelectAdcSincFilter.setItemText(3, _translate("MainWindow", "Sinc3 Fast", None))
        self.cboSelectAdcSincFilter.setItemText(4, _translate("MainWindow", "Post Filter", None))
        self.chkRej60.setText(_translate("MainWindow", "Reject 60 Hz", None))
        self.lblCboAdcFilterDataRate.setText(_translate("MainWindow", "Select Filter Data Rate (1 to 2047)", None))
        self.btnSetFilterDataRate.setText(_translate("MainWindow", "Set", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAdcConfig), _translate("MainWindow", "ADC Config", None))
        self.btnReadLoop1Settings.setText(_translate("MainWindow", "Read Loop 1 Settings", None))
        self.btnReadLoop2Settings.setText(_translate("MainWindow", "Read Loop 2 Settings", None))
        self.lblProportional1.setText(_translate("MainWindow", "Proportional(0 to 100)", None))
        self.btnSetPterm1.setText(_translate("MainWindow", "Set", None))
        self.lblIntegral1.setText(_translate("MainWindow", "Integral (0 to 100)", None))
        self.btnSetIterm1.setText(_translate("MainWindow", "Set", None))
        self.btnSetDterm1.setText(_translate("MainWindow", "Set", None))
        self.lblDerivative1.setText(_translate("MainWindow", "Derivative (0 to 100)", None))
        self.lblSelLoopSns1.setText(_translate("MainWindow", "Select Loop Sensor", None))
        self.cboSelLoopSns1.setItemText(0, _translate("MainWindow", "Sensor 1", None))
        self.cboSelLoopSns1.setItemText(1, _translate("MainWindow", "Sensor 2", None))
        self.cboSelLoopSns1.setItemText(2, _translate("MainWindow", "Sensor 3", None))
        self.cboSelLoopSns1.setItemText(3, _translate("MainWindow", "Sensor 4", None))
        self.cboSelLoopSns1.setItemText(4, _translate("MainWindow", "Sensor 5", None))
        self.cboSelLoopSns1.setItemText(5, _translate("MainWindow", "Sensor 6", None))
        self.cboSelLoopSns1.setItemText(6, _translate("MainWindow", "Sensor 7", None))
        self.cboSelLoopSns1.setItemText(7, _translate("MainWindow", "Sensor 8", None))
        self.cboSelLoopSns1.setItemText(8, _translate("MainWindow", "Sensor 9", None))
        self.cboSelLoopSns1.setItemText(9, _translate("MainWindow", "Sensor 10", None))
        self.cboSelLoopSns1.setItemText(10, _translate("MainWindow", "Sensor 11", None))
        self.cboSelLoopSns1.setItemText(11, _translate("MainWindow", "Sensor 12", None))
        self.lblSetPoint1.setText(_translate("MainWindow", "Set Point (K)", None))
        self.btnSetSp1.setText(_translate("MainWindow", "Set", None))
        self.lblHtrCruuent1.setText(_translate("MainWindow", "Heater Current (A)", None))
        self.btnSetHtrCurrent1.setText(_translate("MainWindow", "Set", None))
        self.radDisabled1.setText(_translate("MainWindow", "Disabled", None))
        self.radHtrCurrent1.setText(_translate("MainWindow", "Current", None))
        self.radPid1.setText(_translate("MainWindow", "PID", None))
        self.lblIntegral1_2.setText(_translate("MainWindow", "Integral (0 to 100)", None))
        self.lblProportional1_2.setText(_translate("MainWindow", "Proportional(0 to 100)", None))
        self.radPid2.setText(_translate("MainWindow", "PID", None))
        self.lblSetPoint1_2.setText(_translate("MainWindow", "Set Point (K)", None))
        self.cboSelLoopSns2.setItemText(0, _translate("MainWindow", "Sensor 1", None))
        self.cboSelLoopSns2.setItemText(1, _translate("MainWindow", "Sensor 2", None))
        self.cboSelLoopSns2.setItemText(2, _translate("MainWindow", "Sensor 3", None))
        self.cboSelLoopSns2.setItemText(3, _translate("MainWindow", "Sensor 4", None))
        self.cboSelLoopSns2.setItemText(4, _translate("MainWindow", "Sensor 5", None))
        self.cboSelLoopSns2.setItemText(5, _translate("MainWindow", "Sensor 6", None))
        self.cboSelLoopSns2.setItemText(6, _translate("MainWindow", "Sensor 7", None))
        self.cboSelLoopSns2.setItemText(7, _translate("MainWindow", "Sensor 8", None))
        self.cboSelLoopSns2.setItemText(8, _translate("MainWindow", "Sensor 9", None))
        self.cboSelLoopSns2.setItemText(9, _translate("MainWindow", "Sensor 10", None))
        self.cboSelLoopSns2.setItemText(10, _translate("MainWindow", "Sensor 11", None))
        self.cboSelLoopSns2.setItemText(11, _translate("MainWindow", "Sensor 12", None))
        self.lblHtrCruuent1_2.setText(_translate("MainWindow", "Heater Current (A)", None))
        self.btnSetHtrCurrent2.setText(_translate("MainWindow", "Set", None))
        self.lblDerivative1_2.setText(_translate("MainWindow", "Derivative (0 to 100)", None))
        self.radDisabled2.setText(_translate("MainWindow", "Disabled", None))
        self.radHtrCurrent2.setText(_translate("MainWindow", "Current", None))
        self.btnSetDterm2.setText(_translate("MainWindow", "Set", None))
        self.btnSetPterm2.setText(_translate("MainWindow", "Set", None))
        self.btnSetSp2.setText(_translate("MainWindow", "Set", None))
        self.lblSelLoopSns1_2.setText(_translate("MainWindow", "Select Loop Sensor", None))
        self.btnSetIterm2.setText(_translate("MainWindow", "Set", None))
        self.chkHighPowerOut1.setText(_translate("MainWindow", "High Power Out1", None))
        self.chkHighPowerOut2.setText(_translate("MainWindow", "High Power Out2", None))
        self.bthHighPowerOutStatus.setText(_translate("MainWindow", "Read Status", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabHeaterLoops), _translate("MainWindow", "HeaterLoops", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDatabase), _translate("MainWindow", "Database", None))

