# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/Sensor Monitor Board/Software/RaspberryPi/ICS_SMB/SmbMainGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMain.setGeometry(QtCore.QRect(50, 20, 581, 611))
        self.tabMain.setBaseSize(QtCore.QSize(0, 0))
        self.tabMain.setObjectName("tabMain")
        self.tabReadings = QtWidgets.QWidget()
        self.tabReadings.setObjectName("tabReadings")
        self.btnReadAdcCounts = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAdcCounts.setGeometry(QtCore.QRect(40, 60, 131, 31))
        self.btnReadAdcCounts.setObjectName("btnReadAdcCounts")
        self.btnReadSensorResistances = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadSensorResistances.setGeometry(QtCore.QRect(40, 150, 131, 41))
        self.btnReadSensorResistances.setObjectName("btnReadSensorResistances")
        self.btnReadSenorVolts = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadSenorVolts.setGeometry(QtCore.QRect(40, 100, 131, 41))
        self.btnReadSenorVolts.setObjectName("btnReadSenorVolts")
        self.btnReadAllTemps = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAllTemps.setGeometry(QtCore.QRect(40, 10, 131, 41))
        self.btnReadAllTemps.setObjectName("btnReadAllTemps")
        self.btnReadHumidity = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadHumidity.setGeometry(QtCore.QRect(40, 300, 131, 31))
        self.btnReadHumidity.setObjectName("btnReadHumidity")
        self.btnRadRefVolts = QtWidgets.QPushButton(self.tabReadings)
        self.btnRadRefVolts.setGeometry(QtCore.QRect(40, 200, 131, 41))
        self.btnRadRefVolts.setObjectName("btnRadRefVolts")
        self.btnReadAdcChipTemps = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAdcChipTemps.setGeometry(QtCore.QRect(40, 250, 131, 41))
        self.btnReadAdcChipTemps.setObjectName("btnReadAdcChipTemps")
        self.tabMain.addTab(self.tabReadings, "")
        self.tabAdcConfig = QtWidgets.QWidget()
        self.tabAdcConfig.setObjectName("tabAdcConfig")
        self.grpAdcs = QtWidgets.QGroupBox(self.tabAdcConfig)
        self.grpAdcs.setGeometry(QtCore.QRect(20, 20, 91, 261))
        self.grpAdcs.setCheckable(False)
        self.grpAdcs.setObjectName("grpAdcs")
        self.chkAdc1 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.chkAdc1.setObjectName("chkAdc1")
        self.chkAdc2 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.chkAdc2.setObjectName("chkAdc2")
        self.chkAdc3 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.chkAdc3.setObjectName("chkAdc3")
        self.chkAdc4 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc4.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.chkAdc4.setObjectName("chkAdc4")
        self.chkAdc8 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc8.setGeometry(QtCore.QRect(20, 160, 71, 20))
        self.chkAdc8.setObjectName("chkAdc8")
        self.chkAdc5 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc5.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.chkAdc5.setObjectName("chkAdc5")
        self.chkAdc7 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc7.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.chkAdc7.setObjectName("chkAdc7")
        self.chkAdc6 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc6.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.chkAdc6.setObjectName("chkAdc6")
        self.chkAdc12 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc12.setGeometry(QtCore.QRect(20, 240, 71, 20))
        self.chkAdc12.setObjectName("chkAdc12")
        self.chkAdc9 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc9.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.chkAdc9.setObjectName("chkAdc9")
        self.chkAdc11 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc11.setGeometry(QtCore.QRect(20, 220, 70, 17))
        self.chkAdc11.setObjectName("chkAdc11")
        self.chkAdc10 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc10.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chkAdc10.setObjectName("chkAdc10")
        self.cboExciationCurrent = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboExciationCurrent.setGeometry(QtCore.QRect(120, 50, 121, 22))
        self.cboExciationCurrent.setObjectName("cboExciationCurrent")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.lblCboExcitationCurent = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboExcitationCurent.setGeometry(QtCore.QRect(120, 30, 121, 16))
        self.lblCboExcitationCurent.setObjectName("lblCboExcitationCurent")
        self.lblCboAdcPostFilter = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboAdcPostFilter.setGeometry(QtCore.QRect(120, 140, 121, 16))
        self.lblCboAdcPostFilter.setObjectName("lblCboAdcPostFilter")
        self.cboSelectAdcPostFilter = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelectAdcPostFilter.setGeometry(QtCore.QRect(120, 160, 121, 22))
        self.cboSelectAdcPostFilter.setObjectName("cboSelectAdcPostFilter")
        self.cboSelectAdcPostFilter.addItem("")
        self.cboSelectAdcPostFilter.addItem("")
        self.cboSelectAdcPostFilter.addItem("")
        self.cboSelectAdcPostFilter.addItem("")
        self.lblCboAdcSincFilter = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboAdcSincFilter.setGeometry(QtCore.QRect(120, 90, 121, 16))
        self.lblCboAdcSincFilter.setObjectName("lblCboAdcSincFilter")
        self.cboSelectAdcSincFilter = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelectAdcSincFilter.setGeometry(QtCore.QRect(120, 110, 121, 22))
        self.cboSelectAdcSincFilter.setObjectName("cboSelectAdcSincFilter")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.chkRej60 = QtWidgets.QCheckBox(self.tabAdcConfig)
        self.chkRej60.setGeometry(QtCore.QRect(120, 200, 111, 17))
        self.chkRej60.setObjectName("chkRej60")
        self.lblCboAdcFilterDataRate = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboAdcFilterDataRate.setGeometry(QtCore.QRect(120, 230, 191, 16))
        self.lblCboAdcFilterDataRate.setObjectName("lblCboAdcFilterDataRate")
        self.spinAdcFilterDataRate = QtWidgets.QSpinBox(self.tabAdcConfig)
        self.spinAdcFilterDataRate.setGeometry(QtCore.QRect(120, 250, 121, 22))
        self.spinAdcFilterDataRate.setMinimum(1)
        self.spinAdcFilterDataRate.setMaximum(2047)
        self.spinAdcFilterDataRate.setObjectName("spinAdcFilterDataRate")
        self.btnSetFilterDataRate = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetFilterDataRate.setGeometry(QtCore.QRect(250, 250, 61, 23))
        self.btnSetFilterDataRate.setObjectName("btnSetFilterDataRate")
        self.tabMain.addTab(self.tabAdcConfig, "")
        self.tabHeaterLoops = QtWidgets.QWidget()
        self.tabHeaterLoops.setObjectName("tabHeaterLoops")
        self.btnReadLoop1Settings = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnReadLoop1Settings.setGeometry(QtCore.QRect(30, 20, 151, 31))
        self.btnReadLoop1Settings.setObjectName("btnReadLoop1Settings")
        self.btnReadLoop2Settings = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnReadLoop2Settings.setGeometry(QtCore.QRect(390, 20, 151, 31))
        self.btnReadLoop2Settings.setObjectName("btnReadLoop2Settings")
        self.SpinDblPterm1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblPterm1.setGeometry(QtCore.QRect(130, 80, 101, 22))
        self.SpinDblPterm1.setMaximum(100.0)
        self.SpinDblPterm1.setObjectName("SpinDblPterm1")
        self.lblProportional1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblProportional1.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.lblProportional1.setObjectName("lblProportional1")
        self.btnSetPterm1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetPterm1.setGeometry(QtCore.QRect(240, 80, 41, 21))
        self.btnSetPterm1.setObjectName("btnSetPterm1")
        self.lblIntegral1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblIntegral1.setGeometry(QtCore.QRect(30, 110, 91, 16))
        self.lblIntegral1.setObjectName("lblIntegral1")
        self.btnSetIterm1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetIterm1.setGeometry(QtCore.QRect(240, 110, 41, 21))
        self.btnSetIterm1.setObjectName("btnSetIterm1")
        self.SpinDblIterm1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblIterm1.setGeometry(QtCore.QRect(130, 110, 101, 22))
        self.SpinDblIterm1.setMaximum(100.0)
        self.SpinDblIterm1.setObjectName("SpinDblIterm1")
        self.btnSetDterm1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetDterm1.setGeometry(QtCore.QRect(240, 140, 41, 21))
        self.btnSetDterm1.setObjectName("btnSetDterm1")
        self.lblDerivative1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblDerivative1.setGeometry(QtCore.QRect(20, 140, 101, 20))
        self.lblDerivative1.setObjectName("lblDerivative1")
        self.SpinDblDterm1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblDterm1.setGeometry(QtCore.QRect(130, 140, 101, 22))
        self.SpinDblDterm1.setMaximum(100.0)
        self.SpinDblDterm1.setObjectName("SpinDblDterm1")
        self.lblSelLoopSns1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSelLoopSns1.setGeometry(QtCore.QRect(20, 180, 101, 20))
        self.lblSelLoopSns1.setObjectName("lblSelLoopSns1")
        self.cboSelLoopSns1 = QtWidgets.QComboBox(self.tabHeaterLoops)
        self.cboSelLoopSns1.setGeometry(QtCore.QRect(130, 180, 91, 22))
        self.cboSelLoopSns1.setObjectName("cboSelLoopSns1")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.SpinDblSetPoint1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblSetPoint1.setGeometry(QtCore.QRect(130, 220, 101, 22))
        self.SpinDblSetPoint1.setMinimum(-273.0)
        self.SpinDblSetPoint1.setMaximum(500.0)
        self.SpinDblSetPoint1.setObjectName("SpinDblSetPoint1")
        self.lblSetPoint1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSetPoint1.setGeometry(QtCore.QRect(60, 220, 61, 20))
        self.lblSetPoint1.setObjectName("lblSetPoint1")
        self.btnSetSp1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetSp1.setGeometry(QtCore.QRect(240, 220, 41, 21))
        self.btnSetSp1.setObjectName("btnSetSp1")
        self.lblHtrCruuent1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblHtrCruuent1.setGeometry(QtCore.QRect(30, 250, 91, 20))
        self.lblHtrCruuent1.setObjectName("lblHtrCruuent1")
        self.btnSetHtrCurrent1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetHtrCurrent1.setGeometry(QtCore.QRect(240, 250, 41, 21))
        self.btnSetHtrCurrent1.setObjectName("btnSetHtrCurrent1")
        self.SpinHtrCurrent1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinHtrCurrent1.setGeometry(QtCore.QRect(130, 250, 101, 22))
        self.SpinHtrCurrent1.setDecimals(3)
        self.SpinHtrCurrent1.setMaximum(0.1)
        self.SpinHtrCurrent1.setSingleStep(0.001)
        self.SpinHtrCurrent1.setObjectName("SpinHtrCurrent1")
        self.radDisabled1 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radDisabled1.setGeometry(QtCore.QRect(130, 300, 82, 17))
        self.radDisabled1.setChecked(True)
        self.radDisabled1.setObjectName("radDisabled1")
        self.groupHtrCtl = QtWidgets.QButtonGroup(MainWindow)
        self.groupHtrCtl.setObjectName("groupHtrCtl")
        self.groupHtrCtl.addButton(self.radDisabled1)
        self.radHtrCurrent1 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radHtrCurrent1.setGeometry(QtCore.QRect(130, 320, 82, 17))
        self.radHtrCurrent1.setObjectName("radHtrCurrent1")
        self.groupHtrCtl.addButton(self.radHtrCurrent1)
        self.radPid1 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radPid1.setGeometry(QtCore.QRect(130, 340, 82, 17))
        self.radPid1.setObjectName("radPid1")
        self.groupHtrCtl.addButton(self.radPid1)
        self.SpinDblDterm2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblDterm2.setGeometry(QtCore.QRect(410, 140, 101, 22))
        self.SpinDblDterm2.setMaximum(100.0)
        self.SpinDblDterm2.setObjectName("SpinDblDterm2")
        self.lblIntegral1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblIntegral1_2.setGeometry(QtCore.QRect(310, 110, 91, 16))
        self.lblIntegral1_2.setObjectName("lblIntegral1_2")
        self.lblProportional1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblProportional1_2.setGeometry(QtCore.QRect(300, 80, 111, 16))
        self.lblProportional1_2.setObjectName("lblProportional1_2")
        self.radPid2 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radPid2.setGeometry(QtCore.QRect(410, 340, 82, 17))
        self.radPid2.setObjectName("radPid2")
        self.SpinDblSetPoint2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblSetPoint2.setGeometry(QtCore.QRect(410, 220, 101, 22))
        self.SpinDblSetPoint2.setMinimum(-273.0)
        self.SpinDblSetPoint2.setMaximum(500.0)
        self.SpinDblSetPoint2.setObjectName("SpinDblSetPoint2")
        self.SpinDblIterm2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblIterm2.setGeometry(QtCore.QRect(410, 110, 101, 22))
        self.SpinDblIterm2.setMaximum(100.0)
        self.SpinDblIterm2.setObjectName("SpinDblIterm2")
        self.lblSetPoint1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSetPoint1_2.setGeometry(QtCore.QRect(340, 220, 61, 20))
        self.lblSetPoint1_2.setObjectName("lblSetPoint1_2")
        self.cboSelLoopSns2 = QtWidgets.QComboBox(self.tabHeaterLoops)
        self.cboSelLoopSns2.setGeometry(QtCore.QRect(410, 180, 91, 22))
        self.cboSelLoopSns2.setObjectName("cboSelLoopSns2")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.lblHtrCruuent1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblHtrCruuent1_2.setGeometry(QtCore.QRect(310, 250, 91, 20))
        self.lblHtrCruuent1_2.setObjectName("lblHtrCruuent1_2")
        self.btnSetHtrCurrent2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetHtrCurrent2.setGeometry(QtCore.QRect(520, 250, 41, 21))
        self.btnSetHtrCurrent2.setObjectName("btnSetHtrCurrent2")
        self.lblDerivative1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblDerivative1_2.setGeometry(QtCore.QRect(300, 140, 101, 20))
        self.lblDerivative1_2.setObjectName("lblDerivative1_2")
        self.SpinDblPterm2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblPterm2.setGeometry(QtCore.QRect(410, 80, 101, 22))
        self.SpinDblPterm2.setMaximum(100.0)
        self.SpinDblPterm2.setObjectName("SpinDblPterm2")
        self.radDisabled2 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radDisabled2.setGeometry(QtCore.QRect(410, 300, 82, 17))
        self.radDisabled2.setChecked(True)
        self.radDisabled2.setObjectName("radDisabled2")
        self.SpinHtrCurrent2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinHtrCurrent2.setGeometry(QtCore.QRect(410, 250, 101, 22))
        self.SpinHtrCurrent2.setDecimals(3)
        self.SpinHtrCurrent2.setMaximum(0.1)
        self.SpinHtrCurrent2.setSingleStep(0.001)
        self.SpinHtrCurrent2.setObjectName("SpinHtrCurrent2")
        self.radHtrCurrent2 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radHtrCurrent2.setGeometry(QtCore.QRect(410, 320, 82, 17))
        self.radHtrCurrent2.setObjectName("radHtrCurrent2")
        self.btnSetDterm2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetDterm2.setGeometry(QtCore.QRect(520, 140, 41, 21))
        self.btnSetDterm2.setObjectName("btnSetDterm2")
        self.btnSetPterm2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetPterm2.setGeometry(QtCore.QRect(520, 80, 41, 21))
        self.btnSetPterm2.setObjectName("btnSetPterm2")
        self.btnSetSp2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetSp2.setGeometry(QtCore.QRect(520, 220, 41, 21))
        self.btnSetSp2.setObjectName("btnSetSp2")
        self.lblSelLoopSns1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSelLoopSns1_2.setGeometry(QtCore.QRect(300, 180, 101, 20))
        self.lblSelLoopSns1_2.setObjectName("lblSelLoopSns1_2")
        self.btnSetIterm2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetIterm2.setGeometry(QtCore.QRect(520, 110, 41, 21))
        self.btnSetIterm2.setObjectName("btnSetIterm2")
        self.line = QtWidgets.QFrame(self.tabHeaterLoops)
        self.line.setGeometry(QtCore.QRect(280, 20, 20, 391))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.chkHighPowerOut1 = QtWidgets.QCheckBox(self.tabHeaterLoops)
        self.chkHighPowerOut1.setGeometry(QtCore.QRect(70, 460, 121, 17))
        self.chkHighPowerOut1.setObjectName("chkHighPowerOut1")
        self.chkHighPowerOut2 = QtWidgets.QCheckBox(self.tabHeaterLoops)
        self.chkHighPowerOut2.setGeometry(QtCore.QRect(70, 480, 121, 17))
        self.chkHighPowerOut2.setObjectName("chkHighPowerOut2")
        self.bthHighPowerOutStatus = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.bthHighPowerOutStatus.setGeometry(QtCore.QRect(70, 510, 91, 23))
        self.bthHighPowerOutStatus.setObjectName("bthHighPowerOutStatus")
        self.btnReadLoop1Settings.raise_()
        self.btnReadLoop2Settings.raise_()
        self.SpinDblPterm1.raise_()
        self.lblProportional1.raise_()
        self.btnSetPterm1.raise_()
        self.lblIntegral1.raise_()
        self.btnSetIterm1.raise_()
        self.SpinDblIterm1.raise_()
        self.btnSetDterm1.raise_()
        self.lblDerivative1.raise_()
        self.SpinDblDterm1.raise_()
        self.lblSelLoopSns1.raise_()
        self.cboSelLoopSns1.raise_()
        self.SpinDblSetPoint1.raise_()
        self.lblSetPoint1.raise_()
        self.btnSetSp1.raise_()
        self.lblHtrCruuent1.raise_()
        self.btnSetHtrCurrent1.raise_()
        self.SpinHtrCurrent1.raise_()
        self.radPid1.raise_()
        self.radHtrCurrent1.raise_()
        self.radDisabled1.raise_()
        self.SpinDblDterm2.raise_()
        self.lblIntegral1_2.raise_()
        self.lblProportional1_2.raise_()
        self.radPid2.raise_()
        self.SpinDblSetPoint2.raise_()
        self.SpinDblIterm2.raise_()
        self.lblSetPoint1_2.raise_()
        self.cboSelLoopSns2.raise_()
        self.lblHtrCruuent1_2.raise_()
        self.btnSetHtrCurrent2.raise_()
        self.lblDerivative1_2.raise_()
        self.SpinDblPterm2.raise_()
        self.radDisabled2.raise_()
        self.SpinHtrCurrent2.raise_()
        self.radHtrCurrent2.raise_()
        self.btnSetDterm2.raise_()
        self.btnSetPterm2.raise_()
        self.btnSetSp2.raise_()
        self.lblSelLoopSns1_2.raise_()
        self.btnSetIterm2.raise_()
        self.line.raise_()
        self.chkHighPowerOut1.raise_()
        self.chkHighPowerOut2.raise_()
        self.bthHighPowerOutStatus.raise_()
        self.tabMain.addTab(self.tabHeaterLoops, "")
        self.tabDatabase = QtWidgets.QWidget()
        self.tabDatabase.setObjectName("tabDatabase")
        self.tableView = QtWidgets.QTableView(self.tabDatabase)
        self.tableView.setGeometry(QtCore.QRect(10, 50, 501, 521))
        self.tableView.setObjectName("tableView")
        self.cboDatabaseTableNames = QtWidgets.QComboBox(self.tabDatabase)
        self.cboDatabaseTableNames.setGeometry(QtCore.QRect(20, 10, 301, 22))
        self.cboDatabaseTableNames.setObjectName("cboDatabaseTableNames")
        self.tabMain.addTab(self.tabDatabase, "")
        self.txtDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtDisplay.setGeometry(QtCore.QRect(640, 40, 291, 591))
        self.txtDisplay.setObjectName("txtDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor Monitor Board"))
        self.btnReadAdcCounts.setText(_translate("MainWindow", "Read A/D Counts"))
        self.btnReadSensorResistances.setText(_translate("MainWindow", "Read RTD \n"
"Resistances"))
        self.btnReadSenorVolts.setText(_translate("MainWindow", "Read RTD\n"
"Voltages"))
        self.btnReadAllTemps.setText(_translate("MainWindow", "Read RTD\n"
"Temperatures"))
        self.btnReadHumidity.setText(_translate("MainWindow", "Read Humidity"))
        self.btnRadRefVolts.setText(_translate("MainWindow", "Read ADC \n"
" Ref Voltages"))
        self.btnReadAdcChipTemps.setText(_translate("MainWindow", "Read ADC \n"
"Chip Temperatures"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabReadings), _translate("MainWindow", "Take Readings"))
        self.grpAdcs.setTitle(_translate("MainWindow", "Select ADCs"))
        self.chkAdc1.setText(_translate("MainWindow", "ADC 1"))
        self.chkAdc2.setText(_translate("MainWindow", "ADC 2"))
        self.chkAdc3.setText(_translate("MainWindow", "ADC 3"))
        self.chkAdc4.setText(_translate("MainWindow", "ADC 4"))
        self.chkAdc8.setText(_translate("MainWindow", "ADC 8"))
        self.chkAdc5.setText(_translate("MainWindow", "ADC 5"))
        self.chkAdc7.setText(_translate("MainWindow", "ADC 7"))
        self.chkAdc6.setText(_translate("MainWindow", "ADC 6"))
        self.chkAdc12.setText(_translate("MainWindow", "ADC 12"))
        self.chkAdc9.setText(_translate("MainWindow", "ADC 9"))
        self.chkAdc11.setText(_translate("MainWindow", "ADC 11"))
        self.chkAdc10.setText(_translate("MainWindow", "ADC 10"))
        self.cboExciationCurrent.setItemText(0, _translate("MainWindow", "NONE"))
        self.cboExciationCurrent.setItemText(1, _translate("MainWindow", "50uA"))
        self.cboExciationCurrent.setItemText(2, _translate("MainWindow", "100uA"))
        self.cboExciationCurrent.setItemText(3, _translate("MainWindow", "250uA"))
        self.cboExciationCurrent.setItemText(4, _translate("MainWindow", "500uA"))
        self.cboExciationCurrent.setItemText(5, _translate("MainWindow", "1mA"))
        self.lblCboExcitationCurent.setText(_translate("MainWindow", "Excitation Current"))
        self.lblCboAdcPostFilter.setText(_translate("MainWindow", "Select ADC Post Filter"))
        self.cboSelectAdcPostFilter.setItemText(0, _translate("MainWindow", "47dB"))
        self.cboSelectAdcPostFilter.setItemText(1, _translate("MainWindow", "62dB"))
        self.cboSelectAdcPostFilter.setItemText(2, _translate("MainWindow", "86dB"))
        self.cboSelectAdcPostFilter.setItemText(3, _translate("MainWindow", "92dB"))
        self.lblCboAdcSincFilter.setText(_translate("MainWindow", "Select ADC Sinc Filter"))
        self.cboSelectAdcSincFilter.setItemText(0, _translate("MainWindow", "Sinc4"))
        self.cboSelectAdcSincFilter.setItemText(1, _translate("MainWindow", "Sinc3"))
        self.cboSelectAdcSincFilter.setItemText(2, _translate("MainWindow", "Sinc4 Fast"))
        self.cboSelectAdcSincFilter.setItemText(3, _translate("MainWindow", "Sinc3 Fast"))
        self.cboSelectAdcSincFilter.setItemText(4, _translate("MainWindow", "Post Filter"))
        self.chkRej60.setText(_translate("MainWindow", "Reject 60 Hz"))
        self.lblCboAdcFilterDataRate.setText(_translate("MainWindow", "Select Filter Data Rate (1 to 2047)"))
        self.btnSetFilterDataRate.setText(_translate("MainWindow", "Set"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAdcConfig), _translate("MainWindow", "ADC Config"))
        self.btnReadLoop1Settings.setText(_translate("MainWindow", "Read Loop 1 Settings"))
        self.btnReadLoop2Settings.setText(_translate("MainWindow", "Read Loop 2 Settings"))
        self.lblProportional1.setText(_translate("MainWindow", "Proportional(0 to 100)"))
        self.btnSetPterm1.setText(_translate("MainWindow", "Set"))
        self.lblIntegral1.setText(_translate("MainWindow", "Integral (0 to 100)"))
        self.btnSetIterm1.setText(_translate("MainWindow", "Set"))
        self.btnSetDterm1.setText(_translate("MainWindow", "Set"))
        self.lblDerivative1.setText(_translate("MainWindow", "Derivative (0 to 100)"))
        self.lblSelLoopSns1.setText(_translate("MainWindow", "Select Loop Sensor"))
        self.cboSelLoopSns1.setItemText(0, _translate("MainWindow", "Sensor 1"))
        self.cboSelLoopSns1.setItemText(1, _translate("MainWindow", "Sensor 2"))
        self.cboSelLoopSns1.setItemText(2, _translate("MainWindow", "Sensor 3"))
        self.cboSelLoopSns1.setItemText(3, _translate("MainWindow", "Sensor 4"))
        self.cboSelLoopSns1.setItemText(4, _translate("MainWindow", "Sensor 5"))
        self.cboSelLoopSns1.setItemText(5, _translate("MainWindow", "Sensor 6"))
        self.cboSelLoopSns1.setItemText(6, _translate("MainWindow", "Sensor 7"))
        self.cboSelLoopSns1.setItemText(7, _translate("MainWindow", "Sensor 8"))
        self.cboSelLoopSns1.setItemText(8, _translate("MainWindow", "Sensor 9"))
        self.cboSelLoopSns1.setItemText(9, _translate("MainWindow", "Sensor 10"))
        self.cboSelLoopSns1.setItemText(10, _translate("MainWindow", "Sensor 11"))
        self.cboSelLoopSns1.setItemText(11, _translate("MainWindow", "Sensor 12"))
        self.lblSetPoint1.setText(_translate("MainWindow", "Set Point (K)"))
        self.btnSetSp1.setText(_translate("MainWindow", "Set"))
        self.lblHtrCruuent1.setText(_translate("MainWindow", "Heater Current (A)"))
        self.btnSetHtrCurrent1.setText(_translate("MainWindow", "Set"))
        self.radDisabled1.setText(_translate("MainWindow", "Disabled"))
        self.radHtrCurrent1.setText(_translate("MainWindow", "Current"))
        self.radPid1.setText(_translate("MainWindow", "PID"))
        self.lblIntegral1_2.setText(_translate("MainWindow", "Integral (0 to 100)"))
        self.lblProportional1_2.setText(_translate("MainWindow", "Proportional(0 to 100)"))
        self.radPid2.setText(_translate("MainWindow", "PID"))
        self.lblSetPoint1_2.setText(_translate("MainWindow", "Set Point (K)"))
        self.cboSelLoopSns2.setItemText(0, _translate("MainWindow", "Sensor 1"))
        self.cboSelLoopSns2.setItemText(1, _translate("MainWindow", "Sensor 2"))
        self.cboSelLoopSns2.setItemText(2, _translate("MainWindow", "Sensor 3"))
        self.cboSelLoopSns2.setItemText(3, _translate("MainWindow", "Sensor 4"))
        self.cboSelLoopSns2.setItemText(4, _translate("MainWindow", "Sensor 5"))
        self.cboSelLoopSns2.setItemText(5, _translate("MainWindow", "Sensor 6"))
        self.cboSelLoopSns2.setItemText(6, _translate("MainWindow", "Sensor 7"))
        self.cboSelLoopSns2.setItemText(7, _translate("MainWindow", "Sensor 8"))
        self.cboSelLoopSns2.setItemText(8, _translate("MainWindow", "Sensor 9"))
        self.cboSelLoopSns2.setItemText(9, _translate("MainWindow", "Sensor 10"))
        self.cboSelLoopSns2.setItemText(10, _translate("MainWindow", "Sensor 11"))
        self.cboSelLoopSns2.setItemText(11, _translate("MainWindow", "Sensor 12"))
        self.lblHtrCruuent1_2.setText(_translate("MainWindow", "Heater Current (A)"))
        self.btnSetHtrCurrent2.setText(_translate("MainWindow", "Set"))
        self.lblDerivative1_2.setText(_translate("MainWindow", "Derivative (0 to 100)"))
        self.radDisabled2.setText(_translate("MainWindow", "Disabled"))
        self.radHtrCurrent2.setText(_translate("MainWindow", "Current"))
        self.btnSetDterm2.setText(_translate("MainWindow", "Set"))
        self.btnSetPterm2.setText(_translate("MainWindow", "Set"))
        self.btnSetSp2.setText(_translate("MainWindow", "Set"))
        self.lblSelLoopSns1_2.setText(_translate("MainWindow", "Select Loop Sensor"))
        self.btnSetIterm2.setText(_translate("MainWindow", "Set"))
        self.chkHighPowerOut1.setText(_translate("MainWindow", "High Power Out1"))
        self.chkHighPowerOut2.setText(_translate("MainWindow", "High Power Out2"))
        self.bthHighPowerOutStatus.setText(_translate("MainWindow", "Read Status"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabHeaterLoops), _translate("MainWindow", "HeaterLoops"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDatabase), _translate("MainWindow", "Database"))

