# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:/Sensor Monitor Board/Software/RaspberryPi/ICS_SMB/SmbMainGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 686)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMain.setGeometry(QtCore.QRect(50, 50, 621, 611))
        self.tabMain.setBaseSize(QtCore.QSize(0, 0))
        self.tabMain.setStyleSheet("")
        self.tabMain.setObjectName("tabMain")
        self.tabReadings = QtWidgets.QWidget()
        self.tabReadings.setObjectName("tabReadings")
        self.btnReadAdcCountsFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAdcCountsFromTlm.setGeometry(QtCore.QRect(40, 90, 131, 31))
        self.btnReadAdcCountsFromTlm.setObjectName("btnReadAdcCountsFromTlm")
        self.btnReadSensorResistancesFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadSensorResistancesFromTlm.setGeometry(QtCore.QRect(40, 180, 131, 41))
        self.btnReadSensorResistancesFromTlm.setObjectName("btnReadSensorResistancesFromTlm")
        self.btnReadSenorVoltsFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadSenorVoltsFromTlm.setGeometry(QtCore.QRect(40, 130, 131, 41))
        self.btnReadSenorVoltsFromTlm.setObjectName("btnReadSenorVoltsFromTlm")
        self.btnReadAllTempsFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAllTempsFromTlm.setGeometry(QtCore.QRect(40, 40, 131, 41))
        self.btnReadAllTempsFromTlm.setStyleSheet("QMainWindw{\n"
"background: redrgb(170, 0, 255)\n"
"}")
        self.btnReadAllTempsFromTlm.setObjectName("btnReadAllTempsFromTlm")
        self.btnReadHumidityFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadHumidityFromTlm.setGeometry(QtCore.QRect(40, 330, 131, 31))
        self.btnReadHumidityFromTlm.setObjectName("btnReadHumidityFromTlm")
        self.btnRadRefVoltsFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnRadRefVoltsFromTlm.setGeometry(QtCore.QRect(40, 230, 131, 41))
        self.btnRadRefVoltsFromTlm.setObjectName("btnRadRefVoltsFromTlm")
        self.btnReadAdcChipTempsFromTlm = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAdcChipTempsFromTlm.setGeometry(QtCore.QRect(40, 280, 131, 41))
        self.btnReadAdcChipTempsFromTlm.setObjectName("btnReadAdcChipTempsFromTlm")
        self.cboSelAdcTemp = QtWidgets.QComboBox(self.tabReadings)
        self.cboSelAdcTemp.setGeometry(QtCore.QRect(250, 50, 121, 22))
        self.cboSelAdcTemp.setMaxVisibleItems(12)
        self.cboSelAdcTemp.setObjectName("cboSelAdcTemp")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.cboSelAdcTemp.addItem("")
        self.btnReadAdcCountsFromChip = QtWidgets.QPushButton(self.tabReadings)
        self.btnReadAdcCountsFromChip.setGeometry(QtCore.QRect(380, 50, 131, 31))
        self.btnReadAdcCountsFromChip.setObjectName("btnReadAdcCountsFromChip")
        self.tabMain.addTab(self.tabReadings, "")
        self.tabAdcConfig = QtWidgets.QWidget()
        self.tabAdcConfig.setObjectName("tabAdcConfig")
        self.grpAdcs = QtWidgets.QGroupBox(self.tabAdcConfig)
        self.grpAdcs.setGeometry(QtCore.QRect(20, 20, 91, 261))
        self.grpAdcs.setCheckable(False)
        self.grpAdcs.setObjectName("grpAdcs")
        self.chkAdc1 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc1.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.chkAdc1.setObjectName("chkAdc1")
        self.chkAdc2 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc2.setGeometry(QtCore.QRect(20, 40, 70, 17))
        self.chkAdc2.setObjectName("chkAdc2")
        self.chkAdc3 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc3.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.chkAdc3.setObjectName("chkAdc3")
        self.chkAdc4 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc4.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.chkAdc4.setObjectName("chkAdc4")
        self.chkAdc8 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc8.setGeometry(QtCore.QRect(20, 160, 71, 20))
        self.chkAdc8.setObjectName("chkAdc8")
        self.chkAdc5 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc5.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.chkAdc5.setObjectName("chkAdc5")
        self.chkAdc7 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc7.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.chkAdc7.setObjectName("chkAdc7")
        self.chkAdc6 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc6.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.chkAdc6.setObjectName("chkAdc6")
        self.chkAdc12 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc12.setGeometry(QtCore.QRect(20, 240, 71, 20))
        self.chkAdc12.setObjectName("chkAdc12")
        self.chkAdc9 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc9.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.chkAdc9.setObjectName("chkAdc9")
        self.chkAdc11 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc11.setGeometry(QtCore.QRect(20, 220, 70, 17))
        self.chkAdc11.setObjectName("chkAdc11")
        self.chkAdc10 = QtWidgets.QCheckBox(self.grpAdcs)
        self.chkAdc10.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chkAdc10.setObjectName("chkAdc10")
        self.cboExciationCurrent = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboExciationCurrent.setGeometry(QtCore.QRect(120, 190, 121, 22))
        self.cboExciationCurrent.setObjectName("cboExciationCurrent")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.cboExciationCurrent.addItem("")
        self.lblCboExcitationCurent = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboExcitationCurent.setGeometry(QtCore.QRect(120, 170, 171, 16))
        self.lblCboExcitationCurent.setObjectName("lblCboExcitationCurent")
        self.lblCboAdcPostFilter = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboAdcPostFilter.setGeometry(QtCore.QRect(120, 270, 171, 16))
        self.lblCboAdcPostFilter.setObjectName("lblCboAdcPostFilter")
        self.cboSelectAdcPostFilter = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelectAdcPostFilter.setGeometry(QtCore.QRect(120, 290, 121, 22))
        self.cboSelectAdcPostFilter.setObjectName("cboSelectAdcPostFilter")
        self.cboSelectAdcPostFilter.addItem("")
        self.cboSelectAdcPostFilter.addItem("")
        self.cboSelectAdcPostFilter.addItem("")
        self.cboSelectAdcPostFilter.addItem("")
        self.lblCboAdcSincFilter = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboAdcSincFilter.setGeometry(QtCore.QRect(120, 220, 171, 16))
        self.lblCboAdcSincFilter.setObjectName("lblCboAdcSincFilter")
        self.cboSelectAdcSincFilter = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelectAdcSincFilter.setGeometry(QtCore.QRect(120, 240, 121, 22))
        self.cboSelectAdcSincFilter.setObjectName("cboSelectAdcSincFilter")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.cboSelectAdcSincFilter.addItem("")
        self.lblCboAdcFilterDataRate = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboAdcFilterDataRate.setGeometry(QtCore.QRect(120, 370, 231, 16))
        self.lblCboAdcFilterDataRate.setObjectName("lblCboAdcFilterDataRate")
        self.spinAdcFilterDataRate = QtWidgets.QSpinBox(self.tabAdcConfig)
        self.spinAdcFilterDataRate.setGeometry(QtCore.QRect(120, 390, 121, 22))
        self.spinAdcFilterDataRate.setMinimum(1)
        self.spinAdcFilterDataRate.setMaximum(2047)
        self.spinAdcFilterDataRate.setObjectName("spinAdcFilterDataRate")
        self.btnSetFilterDataRate = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetFilterDataRate.setGeometry(QtCore.QRect(250, 390, 61, 23))
        self.btnSetFilterDataRate.setObjectName("btnSetFilterDataRate")
        self.cboSelectSensorType = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelectSensorType.setGeometry(QtCore.QRect(120, 90, 121, 22))
        self.cboSelectSensorType.setObjectName("cboSelectSensorType")
        self.cboSelectSensorType.addItem("")
        self.cboSelectSensorType.addItem("")
        self.cboSelectSensorType.addItem("")
        self.lblCboSelectSenor = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboSelectSenor.setGeometry(QtCore.QRect(120, 70, 171, 16))
        self.lblCboSelectSenor.setObjectName("lblCboSelectSenor")
        self.cboSelectTempUnit = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelectTempUnit.setGeometry(QtCore.QRect(120, 40, 121, 22))
        self.cboSelectTempUnit.setObjectName("cboSelectTempUnit")
        self.cboSelectTempUnit.addItem("")
        self.cboSelectTempUnit.addItem("")
        self.cboSelectTempUnit.addItem("")
        self.lblCboSelectTempUnit = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboSelectTempUnit.setGeometry(QtCore.QRect(120, 20, 171, 16))
        self.lblCboSelectTempUnit.setObjectName("lblCboSelectTempUnit")
        self.cboSelAdc = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSelAdc.setGeometry(QtCore.QRect(310, 40, 121, 22))
        self.cboSelAdc.setMaxVisibleItems(12)
        self.cboSelAdc.setObjectName("cboSelAdc")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.cboSelAdc.addItem("")
        self.lblSelAdc = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblSelAdc.setGeometry(QtCore.QRect(310, 20, 121, 16))
        self.lblSelAdc.setObjectName("lblSelAdc")
        self.cboAdcRegisters = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboAdcRegisters.setGeometry(QtCore.QRect(310, 70, 121, 22))
        self.cboAdcRegisters.setObjectName("cboAdcRegisters")
        self.btnReadAdcRegister = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnReadAdcRegister.setGeometry(QtCore.QRect(310, 100, 131, 31))
        self.btnReadAdcRegister.setObjectName("btnReadAdcRegister")
        self.btnSetTempUnit = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetTempUnit.setGeometry(QtCore.QRect(250, 40, 41, 23))
        self.btnSetTempUnit.setObjectName("btnSetTempUnit")
        self.btnSetSensorType = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetSensorType.setGeometry(QtCore.QRect(250, 90, 41, 23))
        self.btnSetSensorType.setObjectName("btnSetSensorType")
        self.btnSetExcitationCurrent = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetExcitationCurrent.setGeometry(QtCore.QRect(250, 190, 41, 23))
        self.btnSetExcitationCurrent.setObjectName("btnSetExcitationCurrent")
        self.btnSetSyncFilter = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetSyncFilter.setGeometry(QtCore.QRect(250, 240, 41, 23))
        self.btnSetSyncFilter.setObjectName("btnSetSyncFilter")
        self.btnSetPostFilter = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetPostFilter.setGeometry(QtCore.QRect(250, 290, 41, 23))
        self.btnSetPostFilter.setObjectName("btnSetPostFilter")
        self.lblCboSensorWiring = QtWidgets.QLabel(self.tabAdcConfig)
        self.lblCboSensorWiring.setGeometry(QtCore.QRect(120, 120, 171, 16))
        self.lblCboSensorWiring.setObjectName("lblCboSensorWiring")
        self.cboSeletSenorWiring = QtWidgets.QComboBox(self.tabAdcConfig)
        self.cboSeletSenorWiring.setGeometry(QtCore.QRect(120, 140, 121, 22))
        self.cboSeletSenorWiring.setObjectName("cboSeletSenorWiring")
        self.cboSeletSenorWiring.addItem("")
        self.cboSeletSenorWiring.addItem("")
        self.btnSetSenorWiring = QtWidgets.QPushButton(self.tabAdcConfig)
        self.btnSetSenorWiring.setGeometry(QtCore.QRect(250, 140, 41, 23))
        self.btnSetSenorWiring.setObjectName("btnSetSenorWiring")
        self.tabMain.addTab(self.tabAdcConfig, "")
        self.tabHeaterLoops = QtWidgets.QWidget()
        self.tabHeaterLoops.setObjectName("tabHeaterLoops")
        self.btnReadLoop1Settings = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnReadLoop1Settings.setGeometry(QtCore.QRect(50, 20, 151, 31))
        self.btnReadLoop1Settings.setObjectName("btnReadLoop1Settings")
        self.btnReadLoop2Settings = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnReadLoop2Settings.setGeometry(QtCore.QRect(350, 20, 151, 31))
        self.btnReadLoop2Settings.setObjectName("btnReadLoop2Settings")
        self.SpinDblPterm1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblPterm1.setGeometry(QtCore.QRect(180, 80, 71, 22))
        self.SpinDblPterm1.setMaximum(100.0)
        self.SpinDblPterm1.setObjectName("SpinDblPterm1")
        self.lblProportional1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblProportional1.setGeometry(QtCore.QRect(10, 80, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblProportional1.setFont(font)
        self.lblProportional1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProportional1.setObjectName("lblProportional1")
        self.btnSetPterm1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetPterm1.setGeometry(QtCore.QRect(260, 80, 41, 21))
        self.btnSetPterm1.setObjectName("btnSetPterm1")
        self.lblIntegral1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblIntegral1.setGeometry(QtCore.QRect(10, 110, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblIntegral1.setFont(font)
        self.lblIntegral1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIntegral1.setObjectName("lblIntegral1")
        self.btnSetIterm1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetIterm1.setGeometry(QtCore.QRect(260, 110, 41, 21))
        self.btnSetIterm1.setObjectName("btnSetIterm1")
        self.SpinDblIterm1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblIterm1.setGeometry(QtCore.QRect(180, 110, 71, 22))
        self.SpinDblIterm1.setMaximum(100.0)
        self.SpinDblIterm1.setObjectName("SpinDblIterm1")
        self.btnSetDterm1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetDterm1.setGeometry(QtCore.QRect(260, 140, 41, 21))
        self.btnSetDterm1.setObjectName("btnSetDterm1")
        self.lblDerivative1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblDerivative1.setGeometry(QtCore.QRect(10, 140, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblDerivative1.setFont(font)
        self.lblDerivative1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDerivative1.setObjectName("lblDerivative1")
        self.SpinDblDterm1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblDterm1.setGeometry(QtCore.QRect(180, 140, 71, 22))
        self.SpinDblDterm1.setMaximum(100.0)
        self.SpinDblDterm1.setObjectName("SpinDblDterm1")
        self.lblSelLoopSns1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSelLoopSns1.setGeometry(QtCore.QRect(10, 180, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblSelLoopSns1.setFont(font)
        self.lblSelLoopSns1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSelLoopSns1.setObjectName("lblSelLoopSns1")
        self.cboSelLoopSns1 = QtWidgets.QComboBox(self.tabHeaterLoops)
        self.cboSelLoopSns1.setGeometry(QtCore.QRect(180, 180, 121, 22))
        self.cboSelLoopSns1.setObjectName("cboSelLoopSns1")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.cboSelLoopSns1.addItem("")
        self.SpinDblSetPoint1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblSetPoint1.setGeometry(QtCore.QRect(180, 220, 71, 22))
        self.SpinDblSetPoint1.setMinimum(-273.0)
        self.SpinDblSetPoint1.setMaximum(500.0)
        self.SpinDblSetPoint1.setObjectName("SpinDblSetPoint1")
        self.lblSetPoint1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSetPoint1.setGeometry(QtCore.QRect(10, 220, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblSetPoint1.setFont(font)
        self.lblSetPoint1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSetPoint1.setObjectName("lblSetPoint1")
        self.btnSetSp1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetSp1.setGeometry(QtCore.QRect(260, 220, 41, 21))
        self.btnSetSp1.setObjectName("btnSetSp1")
        self.lblHtrCruuent1 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblHtrCruuent1.setGeometry(QtCore.QRect(10, 250, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblHtrCruuent1.setFont(font)
        self.lblHtrCruuent1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHtrCruuent1.setObjectName("lblHtrCruuent1")
        self.btnSetHtrCurrent1 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetHtrCurrent1.setGeometry(QtCore.QRect(260, 250, 41, 21))
        self.btnSetHtrCurrent1.setObjectName("btnSetHtrCurrent1")
        self.SpinHtrCurrent1 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinHtrCurrent1.setGeometry(QtCore.QRect(180, 250, 71, 22))
        self.SpinHtrCurrent1.setDecimals(3)
        self.SpinHtrCurrent1.setMaximum(0.096)
        self.SpinHtrCurrent1.setSingleStep(0.001)
        self.SpinHtrCurrent1.setObjectName("SpinHtrCurrent1")
        self.radDisabled1 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radDisabled1.setGeometry(QtCore.QRect(150, 300, 82, 17))
        self.radDisabled1.setChecked(True)
        self.radDisabled1.setObjectName("radDisabled1")
        self.groupHtrCtl1 = QtWidgets.QButtonGroup(MainWindow)
        self.groupHtrCtl1.setObjectName("groupHtrCtl1")
        self.groupHtrCtl1.addButton(self.radDisabled1)
        self.radHtrCurrent1 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radHtrCurrent1.setGeometry(QtCore.QRect(150, 320, 82, 17))
        self.radHtrCurrent1.setObjectName("radHtrCurrent1")
        self.groupHtrCtl1.addButton(self.radHtrCurrent1)
        self.radPid1 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radPid1.setGeometry(QtCore.QRect(150, 340, 82, 17))
        self.radPid1.setObjectName("radPid1")
        self.groupHtrCtl1.addButton(self.radPid1)
        self.SpinDblDterm2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblDterm2.setGeometry(QtCore.QRect(480, 140, 71, 22))
        self.SpinDblDterm2.setMaximum(100.0)
        self.SpinDblDterm2.setObjectName("SpinDblDterm2")
        self.lblIntegral1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblIntegral1_2.setGeometry(QtCore.QRect(320, 110, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblIntegral1_2.setFont(font)
        self.lblIntegral1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIntegral1_2.setObjectName("lblIntegral1_2")
        self.lblProportional1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblProportional1_2.setGeometry(QtCore.QRect(320, 80, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblProportional1_2.setFont(font)
        self.lblProportional1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProportional1_2.setObjectName("lblProportional1_2")
        self.radPid2 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radPid2.setGeometry(QtCore.QRect(450, 340, 82, 17))
        self.radPid2.setObjectName("radPid2")
        self.groupHtrCtl2 = QtWidgets.QButtonGroup(MainWindow)
        self.groupHtrCtl2.setObjectName("groupHtrCtl2")
        self.groupHtrCtl2.addButton(self.radPid2)
        self.SpinDblSetPoint2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblSetPoint2.setGeometry(QtCore.QRect(480, 220, 71, 22))
        self.SpinDblSetPoint2.setMinimum(-273.0)
        self.SpinDblSetPoint2.setMaximum(500.0)
        self.SpinDblSetPoint2.setObjectName("SpinDblSetPoint2")
        self.SpinDblIterm2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblIterm2.setGeometry(QtCore.QRect(480, 110, 71, 22))
        self.SpinDblIterm2.setMaximum(100.0)
        self.SpinDblIterm2.setObjectName("SpinDblIterm2")
        self.lblSetPoint1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSetPoint1_2.setGeometry(QtCore.QRect(320, 220, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblSetPoint1_2.setFont(font)
        self.lblSetPoint1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSetPoint1_2.setObjectName("lblSetPoint1_2")
        self.cboSelLoopSns2 = QtWidgets.QComboBox(self.tabHeaterLoops)
        self.cboSelLoopSns2.setGeometry(QtCore.QRect(480, 180, 121, 22))
        self.cboSelLoopSns2.setObjectName("cboSelLoopSns2")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.cboSelLoopSns2.addItem("")
        self.lblHtrCruuent1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblHtrCruuent1_2.setGeometry(QtCore.QRect(320, 250, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblHtrCruuent1_2.setFont(font)
        self.lblHtrCruuent1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHtrCruuent1_2.setObjectName("lblHtrCruuent1_2")
        self.btnSetHtrCurrent2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetHtrCurrent2.setGeometry(QtCore.QRect(560, 250, 41, 21))
        self.btnSetHtrCurrent2.setObjectName("btnSetHtrCurrent2")
        self.lblDerivative1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblDerivative1_2.setGeometry(QtCore.QRect(320, 140, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblDerivative1_2.setFont(font)
        self.lblDerivative1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDerivative1_2.setObjectName("lblDerivative1_2")
        self.SpinDblPterm2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinDblPterm2.setGeometry(QtCore.QRect(480, 80, 71, 22))
        self.SpinDblPterm2.setMaximum(100.0)
        self.SpinDblPterm2.setObjectName("SpinDblPterm2")
        self.radDisabled2 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radDisabled2.setGeometry(QtCore.QRect(450, 300, 82, 17))
        self.radDisabled2.setChecked(True)
        self.radDisabled2.setObjectName("radDisabled2")
        self.groupHtrCtl2.addButton(self.radDisabled2)
        self.SpinHtrCurrent2 = QtWidgets.QDoubleSpinBox(self.tabHeaterLoops)
        self.SpinHtrCurrent2.setGeometry(QtCore.QRect(480, 250, 71, 22))
        self.SpinHtrCurrent2.setDecimals(3)
        self.SpinHtrCurrent2.setMaximum(0.096)
        self.SpinHtrCurrent2.setSingleStep(0.001)
        self.SpinHtrCurrent2.setObjectName("SpinHtrCurrent2")
        self.radHtrCurrent2 = QtWidgets.QRadioButton(self.tabHeaterLoops)
        self.radHtrCurrent2.setGeometry(QtCore.QRect(450, 320, 82, 17))
        self.radHtrCurrent2.setObjectName("radHtrCurrent2")
        self.groupHtrCtl2.addButton(self.radHtrCurrent2)
        self.btnSetDterm2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetDterm2.setGeometry(QtCore.QRect(560, 140, 41, 21))
        self.btnSetDterm2.setObjectName("btnSetDterm2")
        self.btnSetPterm2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetPterm2.setGeometry(QtCore.QRect(560, 80, 41, 21))
        self.btnSetPterm2.setObjectName("btnSetPterm2")
        self.btnSetSp2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetSp2.setGeometry(QtCore.QRect(560, 220, 41, 21))
        self.btnSetSp2.setObjectName("btnSetSp2")
        self.lblSelLoopSns1_2 = QtWidgets.QLabel(self.tabHeaterLoops)
        self.lblSelLoopSns1_2.setGeometry(QtCore.QRect(320, 180, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lblSelLoopSns1_2.setFont(font)
        self.lblSelLoopSns1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSelLoopSns1_2.setObjectName("lblSelLoopSns1_2")
        self.btnSetIterm2 = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.btnSetIterm2.setGeometry(QtCore.QRect(560, 110, 41, 21))
        self.btnSetIterm2.setObjectName("btnSetIterm2")
        self.line = QtWidgets.QFrame(self.tabHeaterLoops)
        self.line.setGeometry(QtCore.QRect(300, 20, 20, 391))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.chkHighPowerOut1 = QtWidgets.QCheckBox(self.tabHeaterLoops)
        self.chkHighPowerOut1.setGeometry(QtCore.QRect(70, 460, 121, 17))
        self.chkHighPowerOut1.setObjectName("chkHighPowerOut1")
        self.chkHighPowerOut2 = QtWidgets.QCheckBox(self.tabHeaterLoops)
        self.chkHighPowerOut2.setGeometry(QtCore.QRect(70, 480, 121, 17))
        self.chkHighPowerOut2.setObjectName("chkHighPowerOut2")
        self.bthHighPowerOutStatus = QtWidgets.QPushButton(self.tabHeaterLoops)
        self.bthHighPowerOutStatus.setGeometry(QtCore.QRect(70, 510, 91, 23))
        self.bthHighPowerOutStatus.setObjectName("bthHighPowerOutStatus")
        self.btnReadLoop1Settings.raise_()
        self.btnReadLoop2Settings.raise_()
        self.SpinDblPterm1.raise_()
        self.lblProportional1.raise_()
        self.btnSetPterm1.raise_()
        self.lblIntegral1.raise_()
        self.btnSetIterm1.raise_()
        self.SpinDblIterm1.raise_()
        self.btnSetDterm1.raise_()
        self.lblDerivative1.raise_()
        self.SpinDblDterm1.raise_()
        self.lblSelLoopSns1.raise_()
        self.cboSelLoopSns1.raise_()
        self.SpinDblSetPoint1.raise_()
        self.lblSetPoint1.raise_()
        self.btnSetSp1.raise_()
        self.lblHtrCruuent1.raise_()
        self.btnSetHtrCurrent1.raise_()
        self.SpinHtrCurrent1.raise_()
        self.radPid1.raise_()
        self.radHtrCurrent1.raise_()
        self.radDisabled1.raise_()
        self.SpinDblDterm2.raise_()
        self.lblIntegral1_2.raise_()
        self.lblProportional1_2.raise_()
        self.radPid2.raise_()
        self.SpinDblSetPoint2.raise_()
        self.SpinDblIterm2.raise_()
        self.lblSetPoint1_2.raise_()
        self.cboSelLoopSns2.raise_()
        self.lblHtrCruuent1_2.raise_()
        self.btnSetHtrCurrent2.raise_()
        self.lblDerivative1_2.raise_()
        self.SpinDblPterm2.raise_()
        self.radDisabled2.raise_()
        self.SpinHtrCurrent2.raise_()
        self.radHtrCurrent2.raise_()
        self.btnSetDterm2.raise_()
        self.btnSetPterm2.raise_()
        self.btnSetSp2.raise_()
        self.lblSelLoopSns1_2.raise_()
        self.btnSetIterm2.raise_()
        self.line.raise_()
        self.chkHighPowerOut1.raise_()
        self.chkHighPowerOut2.raise_()
        self.bthHighPowerOutStatus.raise_()
        self.tabMain.addTab(self.tabHeaterLoops, "")
        self.tabDatabase = QtWidgets.QWidget()
        self.tabDatabase.setObjectName("tabDatabase")
        self.tableView = QtWidgets.QTableView(self.tabDatabase)
        self.tableView.setGeometry(QtCore.QRect(10, 50, 501, 521))
        self.tableView.setObjectName("tableView")
        self.cboDatabaseTableNames = QtWidgets.QComboBox(self.tabDatabase)
        self.cboDatabaseTableNames.setGeometry(QtCore.QRect(20, 10, 301, 22))
        self.cboDatabaseTableNames.setObjectName("cboDatabaseTableNames")
        self.tabMain.addTab(self.tabDatabase, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(260, 90, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btnReadDacStatus1 = QtWidgets.QPushButton(self.tab)
        self.btnReadDacStatus1.setGeometry(QtCore.QRect(70, 70, 131, 51))
        self.btnReadDacStatus1.setObjectName("btnReadDacStatus1")
        self.btnReadDacStatus2 = QtWidgets.QPushButton(self.tab)
        self.btnReadDacStatus2.setGeometry(QtCore.QRect(350, 70, 131, 51))
        self.btnReadDacStatus2.setObjectName("btnReadDacStatus2")
        self.cboDacRegisters1 = QtWidgets.QComboBox(self.tab)
        self.cboDacRegisters1.setGeometry(QtCore.QRect(10, 20, 231, 22))
        self.cboDacRegisters1.setObjectName("cboDacRegisters1")
        self.cboDacRegisters2 = QtWidgets.QComboBox(self.tab)
        self.cboDacRegisters2.setGeometry(QtCore.QRect(300, 20, 231, 22))
        self.cboDacRegisters2.setObjectName("cboDacRegisters2")
        self.tabMain.addTab(self.tab, "")
        self.txtDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtDisplay.setGeometry(QtCore.QRect(680, 80, 251, 581))
        self.txtDisplay.setObjectName("txtDisplay")
        self.lblBoardId = QtWidgets.QLabel(self.centralwidget)
        self.lblBoardId.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        self.lblBoardId.setFont(font)
        self.lblBoardId.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblBoardId.setScaledContents(False)
        self.lblBoardId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBoardId.setObjectName("lblBoardId")
        self.SpinBoardID = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoardID.setGeometry(QtCore.QRect(120, 10, 101, 22))
        self.SpinBoardID.setDecimals(0)
        self.SpinBoardID.setMaximum(1000000000.0)
        self.SpinBoardID.setObjectName("SpinBoardID")
        self.btnSetBoardID = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetBoardID.setGeometry(QtCore.QRect(230, 10, 51, 23))
        self.btnSetBoardID.setObjectName("btnSetBoardID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor Monitor Board"))
        self.btnReadAdcCountsFromTlm.setText(_translate("MainWindow", "Read A/D Counts"))
        self.btnReadSensorResistancesFromTlm.setText(_translate("MainWindow", "Read RTD \n"
"Resistances"))
        self.btnReadSenorVoltsFromTlm.setText(_translate("MainWindow", "Read RTD\n"
"Voltages"))
        self.btnReadAllTempsFromTlm.setText(_translate("MainWindow", "Read RTD\n"
"Temperatures"))
        self.btnReadHumidityFromTlm.setText(_translate("MainWindow", "Read Humidity"))
        self.btnRadRefVoltsFromTlm.setText(_translate("MainWindow", "Read ADC \n"
" Ref Voltages"))
        self.btnReadAdcChipTempsFromTlm.setText(_translate("MainWindow", "Read ADC \n"
"Chip Temperatures"))
        self.cboSelAdcTemp.setCurrentText(_translate("MainWindow", "ADC-1"))
        self.cboSelAdcTemp.setItemText(0, _translate("MainWindow", "ADC-1"))
        self.cboSelAdcTemp.setItemText(1, _translate("MainWindow", "ADC-2"))
        self.cboSelAdcTemp.setItemText(2, _translate("MainWindow", "ADC-3"))
        self.cboSelAdcTemp.setItemText(3, _translate("MainWindow", "ADC-4"))
        self.cboSelAdcTemp.setItemText(4, _translate("MainWindow", "ADC-5"))
        self.cboSelAdcTemp.setItemText(5, _translate("MainWindow", "ADC-6"))
        self.cboSelAdcTemp.setItemText(6, _translate("MainWindow", "ADC-7"))
        self.cboSelAdcTemp.setItemText(7, _translate("MainWindow", "ADC-8"))
        self.cboSelAdcTemp.setItemText(8, _translate("MainWindow", "ADC-9"))
        self.cboSelAdcTemp.setItemText(9, _translate("MainWindow", "ADC-10"))
        self.cboSelAdcTemp.setItemText(10, _translate("MainWindow", "ADC-11"))
        self.cboSelAdcTemp.setItemText(11, _translate("MainWindow", "ADC-12"))
        self.btnReadAdcCountsFromChip.setText(_translate("MainWindow", "Read A/D Counts"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabReadings), _translate("MainWindow", "Take Readings"))
        self.grpAdcs.setTitle(_translate("MainWindow", "Select ADCs"))
        self.chkAdc1.setText(_translate("MainWindow", "ADC 1"))
        self.chkAdc2.setText(_translate("MainWindow", "ADC 2"))
        self.chkAdc3.setText(_translate("MainWindow", "ADC 3"))
        self.chkAdc4.setText(_translate("MainWindow", "ADC 4"))
        self.chkAdc8.setText(_translate("MainWindow", "ADC 8"))
        self.chkAdc5.setText(_translate("MainWindow", "ADC 5"))
        self.chkAdc7.setText(_translate("MainWindow", "ADC 7"))
        self.chkAdc6.setText(_translate("MainWindow", "ADC 6"))
        self.chkAdc12.setText(_translate("MainWindow", "ADC 12"))
        self.chkAdc9.setText(_translate("MainWindow", "ADC 9"))
        self.chkAdc11.setText(_translate("MainWindow", "ADC 11"))
        self.chkAdc10.setText(_translate("MainWindow", "ADC 10"))
        self.cboExciationCurrent.setItemText(0, _translate("MainWindow", "NONE"))
        self.cboExciationCurrent.setItemText(1, _translate("MainWindow", "50uA"))
        self.cboExciationCurrent.setItemText(2, _translate("MainWindow", "100uA"))
        self.cboExciationCurrent.setItemText(3, _translate("MainWindow", "250uA"))
        self.cboExciationCurrent.setItemText(4, _translate("MainWindow", "500uA"))
        self.cboExciationCurrent.setItemText(5, _translate("MainWindow", "750uA"))
        self.cboExciationCurrent.setItemText(6, _translate("MainWindow", "1mA"))
        self.lblCboExcitationCurent.setText(_translate("MainWindow", "Excitation Current"))
        self.lblCboAdcPostFilter.setText(_translate("MainWindow", "Select ADC Post Filter"))
        self.cboSelectAdcPostFilter.setItemText(0, _translate("MainWindow", "47dB (27.27 SPS)"))
        self.cboSelectAdcPostFilter.setItemText(1, _translate("MainWindow", "62dB (25 SPS)"))
        self.cboSelectAdcPostFilter.setItemText(2, _translate("MainWindow", "86dB (20 SPS)"))
        self.cboSelectAdcPostFilter.setItemText(3, _translate("MainWindow", "92dB (16.7 SPS)"))
        self.lblCboAdcSincFilter.setText(_translate("MainWindow", "Select ADC Sinc Filter"))
        self.cboSelectAdcSincFilter.setItemText(0, _translate("MainWindow", "Sinc4"))
        self.cboSelectAdcSincFilter.setItemText(1, _translate("MainWindow", "Sinc3"))
        self.cboSelectAdcSincFilter.setItemText(2, _translate("MainWindow", "Sinc4 Fast"))
        self.cboSelectAdcSincFilter.setItemText(3, _translate("MainWindow", "Sinc3 Fast"))
        self.cboSelectAdcSincFilter.setItemText(4, _translate("MainWindow", "Post Filter"))
        self.lblCboAdcFilterDataRate.setText(_translate("MainWindow", "Select Filter Data Rate (1 to 2047)"))
        self.btnSetFilterDataRate.setText(_translate("MainWindow", "Set"))
        self.cboSelectSensorType.setItemText(0, _translate("MainWindow", "PT100"))
        self.cboSelectSensorType.setItemText(1, _translate("MainWindow", "PT1000"))
        self.cboSelectSensorType.setItemText(2, _translate("MainWindow", "NTC Therm"))
        self.lblCboSelectSenor.setText(_translate("MainWindow", "Sensor Type"))
        self.cboSelectTempUnit.setItemText(0, _translate("MainWindow", "Kelvin"))
        self.cboSelectTempUnit.setItemText(1, _translate("MainWindow", "Celsius"))
        self.cboSelectTempUnit.setItemText(2, _translate("MainWindow", "Fahrenheit"))
        self.lblCboSelectTempUnit.setText(_translate("MainWindow", "Temperature Unit"))
        self.cboSelAdc.setCurrentText(_translate("MainWindow", "ADC-1"))
        self.cboSelAdc.setItemText(0, _translate("MainWindow", "ADC-1"))
        self.cboSelAdc.setItemText(1, _translate("MainWindow", "ADC-2"))
        self.cboSelAdc.setItemText(2, _translate("MainWindow", "ADC-3"))
        self.cboSelAdc.setItemText(3, _translate("MainWindow", "ADC-4"))
        self.cboSelAdc.setItemText(4, _translate("MainWindow", "ADC-5"))
        self.cboSelAdc.setItemText(5, _translate("MainWindow", "ADC-6"))
        self.cboSelAdc.setItemText(6, _translate("MainWindow", "ADC-7"))
        self.cboSelAdc.setItemText(7, _translate("MainWindow", "ADC-8"))
        self.cboSelAdc.setItemText(8, _translate("MainWindow", "ADC-9"))
        self.cboSelAdc.setItemText(9, _translate("MainWindow", "ADC-10"))
        self.cboSelAdc.setItemText(10, _translate("MainWindow", "ADC-11"))
        self.cboSelAdc.setItemText(11, _translate("MainWindow", "ADC-12"))
        self.lblSelAdc.setText(_translate("MainWindow", "Select ADC"))
        self.btnReadAdcRegister.setText(_translate("MainWindow", "Read ADC Register"))
        self.btnSetTempUnit.setText(_translate("MainWindow", "Set"))
        self.btnSetSensorType.setText(_translate("MainWindow", "Set"))
        self.btnSetExcitationCurrent.setText(_translate("MainWindow", "Set"))
        self.btnSetSyncFilter.setText(_translate("MainWindow", "Set"))
        self.btnSetPostFilter.setText(_translate("MainWindow", "Set"))
        self.lblCboSensorWiring.setText(_translate("MainWindow", "Sensor Wiring"))
        self.cboSeletSenorWiring.setItemText(0, _translate("MainWindow", "2 Wire"))
        self.cboSeletSenorWiring.setItemText(1, _translate("MainWindow", "4 Wire"))
        self.btnSetSenorWiring.setText(_translate("MainWindow", "Set"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAdcConfig), _translate("MainWindow", "ADC Config"))
        self.btnReadLoop1Settings.setText(_translate("MainWindow", "Read Loop 1 Settings"))
        self.btnReadLoop2Settings.setText(_translate("MainWindow", "Read Loop 2 Settings"))
        self.lblProportional1.setText(_translate("MainWindow", "Proportional(0 to 100)"))
        self.btnSetPterm1.setText(_translate("MainWindow", "Set"))
        self.lblIntegral1.setText(_translate("MainWindow", "Integral (0 to 100)"))
        self.btnSetIterm1.setText(_translate("MainWindow", "Set"))
        self.btnSetDterm1.setText(_translate("MainWindow", "Set"))
        self.lblDerivative1.setText(_translate("MainWindow", "Derivative (0 to 100)"))
        self.lblSelLoopSns1.setText(_translate("MainWindow", "Select Loop Sensor"))
        self.cboSelLoopSns1.setItemText(0, _translate("MainWindow", "Sensor 1"))
        self.cboSelLoopSns1.setItemText(1, _translate("MainWindow", "Sensor 2"))
        self.cboSelLoopSns1.setItemText(2, _translate("MainWindow", "Sensor 3"))
        self.cboSelLoopSns1.setItemText(3, _translate("MainWindow", "Sensor 4"))
        self.cboSelLoopSns1.setItemText(4, _translate("MainWindow", "Sensor 5"))
        self.cboSelLoopSns1.setItemText(5, _translate("MainWindow", "Sensor 6"))
        self.cboSelLoopSns1.setItemText(6, _translate("MainWindow", "Sensor 7"))
        self.cboSelLoopSns1.setItemText(7, _translate("MainWindow", "Sensor 8"))
        self.cboSelLoopSns1.setItemText(8, _translate("MainWindow", "Sensor 9"))
        self.cboSelLoopSns1.setItemText(9, _translate("MainWindow", "Sensor 10"))
        self.cboSelLoopSns1.setItemText(10, _translate("MainWindow", "Sensor 11"))
        self.cboSelLoopSns1.setItemText(11, _translate("MainWindow", "Sensor 12"))
        self.lblSetPoint1.setText(_translate("MainWindow", "Set Point (K)"))
        self.btnSetSp1.setText(_translate("MainWindow", "Set"))
        self.lblHtrCruuent1.setText(_translate("MainWindow", "Heater Current (A)"))
        self.btnSetHtrCurrent1.setText(_translate("MainWindow", "Set"))
        self.radDisabled1.setText(_translate("MainWindow", "Disabled"))
        self.radHtrCurrent1.setText(_translate("MainWindow", "Current"))
        self.radPid1.setText(_translate("MainWindow", "PID"))
        self.lblIntegral1_2.setText(_translate("MainWindow", "Integral (0 to 100)"))
        self.lblProportional1_2.setText(_translate("MainWindow", "Proportional(0 to 100)"))
        self.radPid2.setText(_translate("MainWindow", "PID"))
        self.lblSetPoint1_2.setText(_translate("MainWindow", "Set Point (K)"))
        self.cboSelLoopSns2.setItemText(0, _translate("MainWindow", "Sensor 1"))
        self.cboSelLoopSns2.setItemText(1, _translate("MainWindow", "Sensor 2"))
        self.cboSelLoopSns2.setItemText(2, _translate("MainWindow", "Sensor 3"))
        self.cboSelLoopSns2.setItemText(3, _translate("MainWindow", "Sensor 4"))
        self.cboSelLoopSns2.setItemText(4, _translate("MainWindow", "Sensor 5"))
        self.cboSelLoopSns2.setItemText(5, _translate("MainWindow", "Sensor 6"))
        self.cboSelLoopSns2.setItemText(6, _translate("MainWindow", "Sensor 7"))
        self.cboSelLoopSns2.setItemText(7, _translate("MainWindow", "Sensor 8"))
        self.cboSelLoopSns2.setItemText(8, _translate("MainWindow", "Sensor 9"))
        self.cboSelLoopSns2.setItemText(9, _translate("MainWindow", "Sensor 10"))
        self.cboSelLoopSns2.setItemText(10, _translate("MainWindow", "Sensor 11"))
        self.cboSelLoopSns2.setItemText(11, _translate("MainWindow", "Sensor 12"))
        self.lblHtrCruuent1_2.setText(_translate("MainWindow", "Heater Current (A)"))
        self.btnSetHtrCurrent2.setText(_translate("MainWindow", "Set"))
        self.lblDerivative1_2.setText(_translate("MainWindow", "Derivative (0 to 100)"))
        self.radDisabled2.setText(_translate("MainWindow", "Disabled"))
        self.radHtrCurrent2.setText(_translate("MainWindow", "Current"))
        self.btnSetDterm2.setText(_translate("MainWindow", "Set"))
        self.btnSetPterm2.setText(_translate("MainWindow", "Set"))
        self.btnSetSp2.setText(_translate("MainWindow", "Set"))
        self.lblSelLoopSns1_2.setText(_translate("MainWindow", "Select Loop Sensor"))
        self.btnSetIterm2.setText(_translate("MainWindow", "Set"))
        self.chkHighPowerOut1.setText(_translate("MainWindow", "High Power Out1"))
        self.chkHighPowerOut2.setText(_translate("MainWindow", "High Power Out2"))
        self.bthHighPowerOutStatus.setText(_translate("MainWindow", "Read Status"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabHeaterLoops), _translate("MainWindow", "HeaterLoops"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDatabase), _translate("MainWindow", "Database"))
        self.btnReadDacStatus1.setText(_translate("MainWindow", "Read DAC Register"))
        self.btnReadDacStatus2.setText(_translate("MainWindow", "Read DAC Register"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab), _translate("MainWindow", "DACs"))
        self.lblBoardId.setText(_translate("MainWindow", "Board ID ="))
        self.btnSetBoardID.setText(_translate("MainWindow", "Set"))

